// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: ateworker.proto

package ateworkerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Worker_RunWorkload_FullMethodName            = "/ateworker.Worker/RunWorkload"
	Worker_CheckpointWorkload_FullMethodName     = "/ateworker.Worker/CheckpointWorkload"
	Worker_RestoreWorkload_FullMethodName        = "/ateworker.Worker/RestoreWorkload"
	Worker_GetWorkloadStats_FullMethodName       = "/ateworker.Worker/GetWorkloadStats"
	Worker_GetActiveWorkloadStats_FullMethodName = "/ateworker.Worker/GetActiveWorkloadStats"
	Worker_TerminateWorkload_FullMethodName      = "/ateworker.Worker/TerminateWorkload"
)

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Worker is the interface to control a single gVisor (or, in the future microVM)
// guest inside a worker pod.
//
// Each worker has two main states, "available" and "executing".
//
// When the worker is "available", the substrate control plane is free to either
// boot a new workload (using RunWorkload), or restore an existing workload from
// a checkpoint (using RestoreWorkload).  These calls move the worker into
// "executing" state.
//
// When the worker is "executing", the substrate control plane can checkpoint the
// running workload (with CheckpointWorkload).  This moves the worker back to
// "free" state.
type WorkerClient interface {
	// RunWorkload tells the worker to begin running a new workload (one or more
	// containers, potentially with shared filesystems).
	RunWorkload(ctx context.Context, in *RunWorkloadRequest, opts ...grpc.CallOption) (*RunWorkloadResponse, error)
	// CheckpointWorkload tells the worker to save the current state of the running
	// workload to object storage, and then completely reset itself to a blank
	// state (back to "available" state.)
	CheckpointWorkload(ctx context.Context, in *CheckpointWorkloadRequest, opts ...grpc.CallOption) (*CheckpointWorkloadResponse, error)
	// RestoreWorkload restores a workload from checkpoint that was previously
	// written by CheckpointWorkload.  The worker will handle downloading the correct
	// gVisor / runsc version to match the checkpoint.
	RestoreWorkload(ctx context.Context, in *RestoreWorkloadRequest, opts ...grpc.CallOption) (*RestoreWorkloadResponse, error)
	// GetWorkloadStats returns a point-in-time resource-usage sample for the
	// workload this worker is currently executing.
	//
	// It is a pure read: unlike the three calls above it does not move the worker
	// between "available" and "executing", so it is safe to call on a timer for
	// the whole lifetime of a workload. It also does not wait on them. Those
	// three serialize on a mutex a worker holds for a whole boot, restore, or
	// checkpoint; this call reads its state from outside that mutex, so a poll
	// landing in the middle of one answers immediately instead of going quiet for
	// the duration -- which would silence the poller during exactly the phases
	// whose usage is most interesting.
	//
	// Two ways it declines to give a sample, and they ask different things of the
	// caller:
	//
	//   * NOT_FOUND -- this worker is not executing the actor in the request. It
	//     may be "available", or a recycled worker may have moved on to a
	//     different actor. Retrying on the same timer will not change the answer:
	//     the caller's worker-to-actor mapping is stale and wants re-resolving.
	//
	//   * FAILED_PRECONDITION -- this worker is executing the requested actor but
	//     has no sample to give yet. It accepts an actor before the sandbox it
	//     will measure exists, so a poll landing in the boot lands here. Read it
	//     as "no numbers right now", not as "the actor is gone": it is transient,
	//     and the caller should skip this sample and take the next one.
	//
	// The split is worth the two codes because the identity is retained from the
	// moment the worker accepts the actor, on both runtimes. That is what makes
	// "booting" distinguishable from "not here" at all, and it means a workload
	// that dies during boot is attributable rather than anonymous.
	GetWorkloadStats(ctx context.Context, in *GetWorkloadStatsRequest, opts ...grpc.CallOption) (*GetWorkloadStatsResponse, error)
	// GetActiveWorkloadStats samples whatever this worker is currently
	// executing, without asserting an identity. It is the discovery read for a
	// scraper that enumerates workers and holds no worker-to-actor mapping;
	// GetWorkloadStats above is the verified read for a caller that must be
	// answered about a specific actor.
	//
	// Every state a blind caller can find is a normal answer here, never an
	// error: an "available" worker answers an empty samples list, and a workload
	// with nothing to measure YET (a poll landing in a boot or a restore)
	// appears as a sample carrying its attribution with
	// source = STATS_SOURCE_UNSPECIFIED -- "not measured", per the sample's own
	// contract -- so even a workload that dies during boot is attributable, not
	// anonymous. Error codes are reserved for real failures reading a sandbox
	// that should be measurable. This is deliberately unlike GetWorkloadStats,
	// whose caller asserts knowledge the codes then answer.
	//
	// Consumers MUST attribute each sample solely from the identity echoed
	// inside it, never from a mapping they hold: without an asserted uid, the
	// response is the only statement of who was measured. Like GetWorkloadStats
	// it is a pure read, safe on a timer, and does not touch the lifecycle
	// mutex.
	GetActiveWorkloadStats(ctx context.Context, in *GetActiveWorkloadStatsRequest, opts ...grpc.CallOption) (*GetActiveWorkloadStatsResponse, error)
	// TerminateWorkload stops and deletes container workloads and cleans up
	// network and bundle overlays on the worker.
	TerminateWorkload(ctx context.Context, in *TerminateWorkloadRequest, opts ...grpc.CallOption) (*TerminateWorkloadResponse, error)
}

type workerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerClient(cc grpc.ClientConnInterface) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) RunWorkload(ctx context.Context, in *RunWorkloadRequest, opts ...grpc.CallOption) (*RunWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunWorkloadResponse)
	err := c.cc.Invoke(ctx, Worker_RunWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) CheckpointWorkload(ctx context.Context, in *CheckpointWorkloadRequest, opts ...grpc.CallOption) (*CheckpointWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointWorkloadResponse)
	err := c.cc.Invoke(ctx, Worker_CheckpointWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) RestoreWorkload(ctx context.Context, in *RestoreWorkloadRequest, opts ...grpc.CallOption) (*RestoreWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreWorkloadResponse)
	err := c.cc.Invoke(ctx, Worker_RestoreWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) GetWorkloadStats(ctx context.Context, in *GetWorkloadStatsRequest, opts ...grpc.CallOption) (*GetWorkloadStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkloadStatsResponse)
	err := c.cc.Invoke(ctx, Worker_GetWorkloadStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) GetActiveWorkloadStats(ctx context.Context, in *GetActiveWorkloadStatsRequest, opts ...grpc.CallOption) (*GetActiveWorkloadStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveWorkloadStatsResponse)
	err := c.cc.Invoke(ctx, Worker_GetActiveWorkloadStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) TerminateWorkload(ctx context.Context, in *TerminateWorkloadRequest, opts ...grpc.CallOption) (*TerminateWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateWorkloadResponse)
	err := c.cc.Invoke(ctx, Worker_TerminateWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
// All implementations must embed UnimplementedWorkerServer
// for forward compatibility.
//
// Worker is the interface to control a single gVisor (or, in the future microVM)
// guest inside a worker pod.
//
// Each worker has two main states, "available" and "executing".
//
// When the worker is "available", the substrate control plane is free to either
// boot a new workload (using RunWorkload), or restore an existing workload from
// a checkpoint (using RestoreWorkload).  These calls move the worker into
// "executing" state.
//
// When the worker is "executing", the substrate control plane can checkpoint the
// running workload (with CheckpointWorkload).  This moves the worker back to
// "free" state.
type WorkerServer interface {
	// RunWorkload tells the worker to begin running a new workload (one or more
	// containers, potentially with shared filesystems).
	RunWorkload(context.Context, *RunWorkloadRequest) (*RunWorkloadResponse, error)
	// CheckpointWorkload tells the worker to save the current state of the running
	// workload to object storage, and then completely reset itself to a blank
	// state (back to "available" state.)
	CheckpointWorkload(context.Context, *CheckpointWorkloadRequest) (*CheckpointWorkloadResponse, error)
	// RestoreWorkload restores a workload from checkpoint that was previously
	// written by CheckpointWorkload.  The worker will handle downloading the correct
	// gVisor / runsc version to match the checkpoint.
	RestoreWorkload(context.Context, *RestoreWorkloadRequest) (*RestoreWorkloadResponse, error)
	// GetWorkloadStats returns a point-in-time resource-usage sample for the
	// workload this worker is currently executing.
	//
	// It is a pure read: unlike the three calls above it does not move the worker
	// between "available" and "executing", so it is safe to call on a timer for
	// the whole lifetime of a workload. It also does not wait on them. Those
	// three serialize on a mutex a worker holds for a whole boot, restore, or
	// checkpoint; this call reads its state from outside that mutex, so a poll
	// landing in the middle of one answers immediately instead of going quiet for
	// the duration -- which would silence the poller during exactly the phases
	// whose usage is most interesting.
	//
	// Two ways it declines to give a sample, and they ask different things of the
	// caller:
	//
	//   * NOT_FOUND -- this worker is not executing the actor in the request. It
	//     may be "available", or a recycled worker may have moved on to a
	//     different actor. Retrying on the same timer will not change the answer:
	//     the caller's worker-to-actor mapping is stale and wants re-resolving.
	//
	//   * FAILED_PRECONDITION -- this worker is executing the requested actor but
	//     has no sample to give yet. It accepts an actor before the sandbox it
	//     will measure exists, so a poll landing in the boot lands here. Read it
	//     as "no numbers right now", not as "the actor is gone": it is transient,
	//     and the caller should skip this sample and take the next one.
	//
	// The split is worth the two codes because the identity is retained from the
	// moment the worker accepts the actor, on both runtimes. That is what makes
	// "booting" distinguishable from "not here" at all, and it means a workload
	// that dies during boot is attributable rather than anonymous.
	GetWorkloadStats(context.Context, *GetWorkloadStatsRequest) (*GetWorkloadStatsResponse, error)
	// GetActiveWorkloadStats samples whatever this worker is currently
	// executing, without asserting an identity. It is the discovery read for a
	// scraper that enumerates workers and holds no worker-to-actor mapping;
	// GetWorkloadStats above is the verified read for a caller that must be
	// answered about a specific actor.
	//
	// Every state a blind caller can find is a normal answer here, never an
	// error: an "available" worker answers an empty samples list, and a workload
	// with nothing to measure YET (a poll landing in a boot or a restore)
	// appears as a sample carrying its attribution with
	// source = STATS_SOURCE_UNSPECIFIED -- "not measured", per the sample's own
	// contract -- so even a workload that dies during boot is attributable, not
	// anonymous. Error codes are reserved for real failures reading a sandbox
	// that should be measurable. This is deliberately unlike GetWorkloadStats,
	// whose caller asserts knowledge the codes then answer.
	//
	// Consumers MUST attribute each sample solely from the identity echoed
	// inside it, never from a mapping they hold: without an asserted uid, the
	// response is the only statement of who was measured. Like GetWorkloadStats
	// it is a pure read, safe on a timer, and does not touch the lifecycle
	// mutex.
	GetActiveWorkloadStats(context.Context, *GetActiveWorkloadStatsRequest) (*GetActiveWorkloadStatsResponse, error)
	// TerminateWorkload stops and deletes container workloads and cleans up
	// network and bundle overlays on the worker.
	TerminateWorkload(context.Context, *TerminateWorkloadRequest) (*TerminateWorkloadResponse, error)
	mustEmbedUnimplementedWorkerServer()
}

// UnimplementedWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServer struct{}

func (UnimplementedWorkerServer) RunWorkload(context.Context, *RunWorkloadRequest) (*RunWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunWorkload not implemented")
}
func (UnimplementedWorkerServer) CheckpointWorkload(context.Context, *CheckpointWorkloadRequest) (*CheckpointWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckpointWorkload not implemented")
}
func (UnimplementedWorkerServer) RestoreWorkload(context.Context, *RestoreWorkloadRequest) (*RestoreWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreWorkload not implemented")
}
func (UnimplementedWorkerServer) GetWorkloadStats(context.Context, *GetWorkloadStatsRequest) (*GetWorkloadStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkloadStats not implemented")
}
func (UnimplementedWorkerServer) GetActiveWorkloadStats(context.Context, *GetActiveWorkloadStatsRequest) (*GetActiveWorkloadStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveWorkloadStats not implemented")
}
func (UnimplementedWorkerServer) TerminateWorkload(context.Context, *TerminateWorkloadRequest) (*TerminateWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateWorkload not implemented")
}
func (UnimplementedWorkerServer) mustEmbedUnimplementedWorkerServer() {}
func (UnimplementedWorkerServer) testEmbeddedByValue()                {}

// UnsafeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServer will
// result in compilation errors.
type UnsafeWorkerServer interface {
	mustEmbedUnimplementedWorkerServer()
}

func RegisterWorkerServer(s grpc.ServiceRegistrar, srv WorkerServer) {
	// If the following call panics, it indicates UnimplementedWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Worker_ServiceDesc, srv)
}

func _Worker_RunWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).RunWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_RunWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).RunWorkload(ctx, req.(*RunWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_CheckpointWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).CheckpointWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_CheckpointWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).CheckpointWorkload(ctx, req.(*CheckpointWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_RestoreWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).RestoreWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_RestoreWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).RestoreWorkload(ctx, req.(*RestoreWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_GetWorkloadStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).GetWorkloadStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_GetWorkloadStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).GetWorkloadStats(ctx, req.(*GetWorkloadStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_GetActiveWorkloadStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveWorkloadStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).GetActiveWorkloadStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_GetActiveWorkloadStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).GetActiveWorkloadStats(ctx, req.(*GetActiveWorkloadStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_TerminateWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).TerminateWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_TerminateWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).TerminateWorkload(ctx, req.(*TerminateWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Worker_ServiceDesc is the grpc.ServiceDesc for Worker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Worker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ateworker.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunWorkload",
			Handler:    _Worker_RunWorkload_Handler,
		},
		{
			MethodName: "CheckpointWorkload",
			Handler:    _Worker_CheckpointWorkload_Handler,
		},
		{
			MethodName: "RestoreWorkload",
			Handler:    _Worker_RestoreWorkload_Handler,
		},
		{
			MethodName: "GetWorkloadStats",
			Handler:    _Worker_GetWorkloadStats_Handler,
		},
		{
			MethodName: "GetActiveWorkloadStats",
			Handler:    _Worker_GetActiveWorkloadStats_Handler,
		},
		{
			MethodName: "TerminateWorkload",
			Handler:    _Worker_TerminateWorkload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ateworker.proto",
}
