//go:build linux

// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// System-info volume support for the micro-VM runtime.
//
// A system-info volume is a read-only directory of files generated by atelet
// on the host on every Run/Restore (e.g. the actorMetadata data-source files),
// so its contents always describe the actor actually being started, whatever
// checkpointed state it boots from. The host side is owned by atelet, which
// creates one directory per volume under
// ateompath.SystemInfoVolumeRootsDir(actorUID) and wipes/rebuilds them when
// the actor's directories are reset.
//
// ateom exposes that host directory to the guest over a THIRD virtiofsd —
// alongside the RO overlay lower (kataShared) and the writable durable-dir
// share — mounted by the agent at sandbox creation. Each volume is a
// subdirectory of the one share, at kata.GuestSystemInfoVolumeDir(volume),
// bind-mounted READ-ONLY from there into every container that declares it.
//
// Unlike durable-dir volumes, system-info volumes are deliberately absent
// from the checkpoint path: their contents must never be captured into
// snapshots (see the SystemInfo semantics in docs/api-guide.md). Like the
// durable share, this one runs with cache=auto: the host contents change
// underneath the guest whenever atelet regenerates them for a restore.

package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/agent-substrate/substrate/cmd/ateom-microvm/internal/kata"
	"github.com/agent-substrate/substrate/internal/ateompath"
	"github.com/agent-substrate/substrate/internal/proto/ateompb"
	specs "github.com/opencontainers/runtime-spec/specs-go"
)

// hasSystemInfoVolumes reports whether any container mounts a system-info
// volume.
func hasSystemInfoVolumes(containers []*ateompb.Container) bool {
	for _, c := range containers {
		if len(c.GetSystemInfoVolumeMounts()) > 0 {
			return true
		}
	}
	return false
}

// systemInfoMounts returns the OCI mounts that expose a container's
// system-info volumes at the paths it declared, read-only. Each source is that
// volume's directory inside the guest's system-info share, which the agent
// mounts at sandbox creation.
func systemInfoMounts(mounts []*ateompb.SystemInfoVolumeMount) []specs.Mount {
	out := make([]specs.Mount, 0, len(mounts))
	for _, m := range mounts {
		out = append(out, specs.Mount{
			Destination: m.GetMountPath(),
			Source:      kata.GuestSystemInfoVolumeDir(m.GetVolumeName()),
			Type:        "bind",
			Options:     []string{"rbind", "ro"},
		})
	}
	return out
}

// systemInfoVirtiofsdLogPath is where the system-info share's virtiofsd logs,
// beside the overlay lower's and the durable share's under the actor's VM dir.
func systemInfoVirtiofsdLogPath(id string) string {
	return filepath.Join(kata.VMDir(id), "virtiofsd-system-info.log")
}

// stageSystemInfoShare starts the virtiofsd serving the actor's system-info
// volumes.
//
// It serves ateompath.SystemInfoVolumeRootsDir directly, like the durable
// share, and runs with cache=auto for the same reason: atelet rewrites the
// contents underneath the guest on every restore. Read-only enforcement
// happens at the container binds (see systemInfoMounts), not here — virtiofsd
// serves the share write-through, and the guest never gets a writable mount
// of it.
//
// The returned cmd outlives this call (CH talks to it for the VM's lifetime);
// the caller owns it (tracked on runningActor, killed in teardownActor).
func (s *AteomService) stageSystemInfoShare(ctx context.Context, rr resolvedRuntime, actorUID string) (*exec.Cmd, error) {
	shared := ateompath.SystemInfoVolumeRootsDir(actorUID)
	if _, err := os.Stat(shared); err != nil {
		return nil, fmt.Errorf("while checking system-info volumes dir %q: %w", shared, err)
	}
	log, _ := os.OpenFile(systemInfoVirtiofsdLogPath(actorUID), os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o600)
	cmd, err := kata.StartVirtiofsd(ctx, kata.VirtiofsdOptions{
		Binary:     rr.virtiofsd,
		SocketPath: kata.SystemInfoVirtiofsdSocketPath(actorUID),
		SharedDir:  shared,
		Cache:      "auto",
		Log:        log,
	})
	if err != nil {
		return nil, fmt.Errorf("while starting system-info virtiofsd: %w", err)
	}
	return cmd, nil
}
