// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: apiconfig.proto

package ateconfigpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The unified configuration object for ate-api-server.
//
// Rules: If you include your configuration setting in the config file, it
// *must* be hot-reloadable using apiconfig.Loader.
type APIConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logging       *APILogging            `protobuf:"bytes,1,opt,name=logging,proto3" json:"logging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIConfig) Reset() {
	*x = APIConfig{}
	mi := &file_apiconfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIConfig) ProtoMessage() {}

func (x *APIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_apiconfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIConfig.ProtoReflect.Descriptor instead.
func (*APIConfig) Descriptor() ([]byte, []int) {
	return file_apiconfig_proto_rawDescGZIP(), []int{0}
}

func (x *APIConfig) GetLogging() *APILogging {
	if x != nil {
		return x.Logging
	}
	return nil
}

type APILogging struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// debug, info, warn, or error
	Level         string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APILogging) Reset() {
	*x = APILogging{}
	mi := &file_apiconfig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APILogging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APILogging) ProtoMessage() {}

func (x *APILogging) ProtoReflect() protoreflect.Message {
	mi := &file_apiconfig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APILogging.ProtoReflect.Descriptor instead.
func (*APILogging) Descriptor() ([]byte, []int) {
	return file_apiconfig_proto_rawDescGZIP(), []int{1}
}

func (x *APILogging) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

var File_apiconfig_proto protoreflect.FileDescriptor

const file_apiconfig_proto_rawDesc = "" +
	"\n" +
	"\x0fapiconfig.proto\x12\vateconfigpb\">\n" +
	"\tAPIConfig\x121\n" +
	"\alogging\x18\x01 \x01(\v2\x17.ateconfigpb.APILoggingR\alogging\"\"\n" +
	"\n" +
	"APILogging\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05levelB2Z0github.com/agent-substrate/pkg/proto/ateconfigpbb\x06proto3"

var (
	file_apiconfig_proto_rawDescOnce sync.Once
	file_apiconfig_proto_rawDescData []byte
)

func file_apiconfig_proto_rawDescGZIP() []byte {
	file_apiconfig_proto_rawDescOnce.Do(func() {
		file_apiconfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiconfig_proto_rawDesc), len(file_apiconfig_proto_rawDesc)))
	})
	return file_apiconfig_proto_rawDescData
}

var file_apiconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apiconfig_proto_goTypes = []any{
	(*APIConfig)(nil),  // 0: ateconfigpb.APIConfig
	(*APILogging)(nil), // 1: ateconfigpb.APILogging
}
var file_apiconfig_proto_depIdxs = []int32{
	1, // 0: ateconfigpb.APIConfig.logging:type_name -> ateconfigpb.APILogging
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apiconfig_proto_init() }
func file_apiconfig_proto_init() {
	if File_apiconfig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiconfig_proto_rawDesc), len(file_apiconfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiconfig_proto_goTypes,
		DependencyIndexes: file_apiconfig_proto_depIdxs,
		MessageInfos:      file_apiconfig_proto_msgTypes,
	}.Build()
	File_apiconfig_proto = out.File
	file_apiconfig_proto_goTypes = nil
	file_apiconfig_proto_depIdxs = nil
}
