// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: atelet.proto

package ateletpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerSupport_MintActorCertificate_FullMethodName = "/atelet.WorkerSupport/MintActorCertificate"
	WorkerSupport_RegisterWorker_FullMethodName       = "/atelet.WorkerSupport/RegisterWorker"
	WorkerSupport_RequestActorSuspend_FullMethodName  = "/atelet.WorkerSupport/RequestActorSuspend"
)

// WorkerSupportClient is the client API for WorkerSupport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerSupport provides callouts for worker implementations.
//
// Called by individual worker pods over a local connection, authenticated with
// the worker's k8s pod identity mTLS certificate.
type WorkerSupportClient interface {
	// Request an atunnel certificate for the given actor.
	//
	// TODO(identity): Rename to MintAtunnelCertificate, as distinct from
	// MintActorCertificate (which would be used for certificates projected into
	// the actor filesystem, when/if we support those).
	MintActorCertificate(ctx context.Context, in *MintActorCertificateRequest, opts ...grpc.CallOption) (*MintActorCertificateResponse, error)
	// Register capacity and hardware identity for this worker with atelet.
	RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error)
	// RequestActorSuspend asks that the actor this worker hosts be suspended,
	// for atelet to forward to the control plane's WorkerService, which this
	// mirrors.
	//
	// Success means the control plane ran the suspend; an error is its refusal,
	// passed through as it was given, so a worker can tell a decision from a
	// failure to ask. Callers must not hold a lock the resulting Checkpoint
	// would need: the control plane answers this by driving a suspend back
	// through atelet into the calling worker.
	RequestActorSuspend(ctx context.Context, in *RequestActorSuspendRequest, opts ...grpc.CallOption) (*RequestActorSuspendResponse, error)
}

type workerSupportClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerSupportClient(cc grpc.ClientConnInterface) WorkerSupportClient {
	return &workerSupportClient{cc}
}

func (c *workerSupportClient) MintActorCertificate(ctx context.Context, in *MintActorCertificateRequest, opts ...grpc.CallOption) (*MintActorCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintActorCertificateResponse)
	err := c.cc.Invoke(ctx, WorkerSupport_MintActorCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerSupportClient) RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWorkerResponse)
	err := c.cc.Invoke(ctx, WorkerSupport_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerSupportClient) RequestActorSuspend(ctx context.Context, in *RequestActorSuspendRequest, opts ...grpc.CallOption) (*RequestActorSuspendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestActorSuspendResponse)
	err := c.cc.Invoke(ctx, WorkerSupport_RequestActorSuspend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerSupportServer is the server API for WorkerSupport service.
// All implementations must embed UnimplementedWorkerSupportServer
// for forward compatibility.
//
// WorkerSupport provides callouts for worker implementations.
//
// Called by individual worker pods over a local connection, authenticated with
// the worker's k8s pod identity mTLS certificate.
type WorkerSupportServer interface {
	// Request an atunnel certificate for the given actor.
	//
	// TODO(identity): Rename to MintAtunnelCertificate, as distinct from
	// MintActorCertificate (which would be used for certificates projected into
	// the actor filesystem, when/if we support those).
	MintActorCertificate(context.Context, *MintActorCertificateRequest) (*MintActorCertificateResponse, error)
	// Register capacity and hardware identity for this worker with atelet.
	RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error)
	// RequestActorSuspend asks that the actor this worker hosts be suspended,
	// for atelet to forward to the control plane's WorkerService, which this
	// mirrors.
	//
	// Success means the control plane ran the suspend; an error is its refusal,
	// passed through as it was given, so a worker can tell a decision from a
	// failure to ask. Callers must not hold a lock the resulting Checkpoint
	// would need: the control plane answers this by driving a suspend back
	// through atelet into the calling worker.
	RequestActorSuspend(context.Context, *RequestActorSuspendRequest) (*RequestActorSuspendResponse, error)
	mustEmbedUnimplementedWorkerSupportServer()
}

// UnimplementedWorkerSupportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerSupportServer struct{}

func (UnimplementedWorkerSupportServer) MintActorCertificate(context.Context, *MintActorCertificateRequest) (*MintActorCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintActorCertificate not implemented")
}
func (UnimplementedWorkerSupportServer) RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedWorkerSupportServer) RequestActorSuspend(context.Context, *RequestActorSuspendRequest) (*RequestActorSuspendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestActorSuspend not implemented")
}
func (UnimplementedWorkerSupportServer) mustEmbedUnimplementedWorkerSupportServer() {}
func (UnimplementedWorkerSupportServer) testEmbeddedByValue()                       {}

// UnsafeWorkerSupportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerSupportServer will
// result in compilation errors.
type UnsafeWorkerSupportServer interface {
	mustEmbedUnimplementedWorkerSupportServer()
}

func RegisterWorkerSupportServer(s grpc.ServiceRegistrar, srv WorkerSupportServer) {
	// If the following call panics, it indicates UnimplementedWorkerSupportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerSupport_ServiceDesc, srv)
}

func _WorkerSupport_MintActorCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintActorCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerSupportServer).MintActorCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerSupport_MintActorCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerSupportServer).MintActorCertificate(ctx, req.(*MintActorCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerSupport_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerSupportServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerSupport_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerSupportServer).RegisterWorker(ctx, req.(*RegisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerSupport_RequestActorSuspend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestActorSuspendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerSupportServer).RequestActorSuspend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerSupport_RequestActorSuspend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerSupportServer).RequestActorSuspend(ctx, req.(*RequestActorSuspendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerSupport_ServiceDesc is the grpc.ServiceDesc for WorkerSupport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerSupport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atelet.WorkerSupport",
	HandlerType: (*WorkerSupportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MintActorCertificate",
			Handler:    _WorkerSupport_MintActorCertificate_Handler,
		},
		{
			MethodName: "RegisterWorker",
			Handler:    _WorkerSupport_RegisterWorker_Handler,
		},
		{
			MethodName: "RequestActorSuspend",
			Handler:    _WorkerSupport_RequestActorSuspend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atelet.proto",
}

const (
	Atelet_Run_FullMethodName                    = "/atelet.Atelet/Run"
	Atelet_Checkpoint_FullMethodName             = "/atelet.Atelet/Checkpoint"
	Atelet_Restore_FullMethodName                = "/atelet.Atelet/Restore"
	Atelet_UploadPausedCheckpoint_FullMethodName = "/atelet.Atelet/UploadPausedCheckpoint"
	Atelet_Terminate_FullMethodName              = "/atelet.Atelet/Terminate"
)

// AteletClient is the client API for Atelet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Atelet allows ate-apiserver to issue control calls to the atelet.
//
// Called by ate-api-server over cluster networking.  ate-api-server
// authenticates with its k8s pod identity mTLS certificate.
type AteletClient interface {
	// Run tells atelet to create a new containerized workload from scratch on a
	// worker.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	// Checkpoint tells atelet to save the current state of the workload on a
	// worker to object storage, and then completely the worker to a blank state
	// (back to "available" state.)
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	// Restore restores a workload from checkpoint onto a worker.
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	// UploadPausedCheckpoint copies a local (pause) checkpoint from this node's
	// disk to object storage. Unlike Checkpoint it drives no worker: the actor is
	// paused, its sandbox is gone; the checkpoint files plus their manifest
	// already sit under the actor's local-checkpoints directory.
	UploadPausedCheckpoint(ctx context.Context, in *UploadPausedCheckpointRequest, opts ...grpc.CallOption) (*UploadPausedCheckpointResponse, error)
	// Terminate tells atelet to terminate/kill any running workload for an actor,
	// unmount its volumes, and clean up actor state on the node.
	Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error)
}

type ateletClient struct {
	cc grpc.ClientConnInterface
}

func NewAteletClient(cc grpc.ClientConnInterface) AteletClient {
	return &ateletClient{cc}
}

func (c *ateletClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, Atelet_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateletClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, Atelet_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateletClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, Atelet_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateletClient) UploadPausedCheckpoint(ctx context.Context, in *UploadPausedCheckpointRequest, opts ...grpc.CallOption) (*UploadPausedCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPausedCheckpointResponse)
	err := c.cc.Invoke(ctx, Atelet_UploadPausedCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateletClient) Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateResponse)
	err := c.cc.Invoke(ctx, Atelet_Terminate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AteletServer is the server API for Atelet service.
// All implementations must embed UnimplementedAteletServer
// for forward compatibility.
//
// Atelet allows ate-apiserver to issue control calls to the atelet.
//
// Called by ate-api-server over cluster networking.  ate-api-server
// authenticates with its k8s pod identity mTLS certificate.
type AteletServer interface {
	// Run tells atelet to create a new containerized workload from scratch on a
	// worker.
	Run(context.Context, *RunRequest) (*RunResponse, error)
	// Checkpoint tells atelet to save the current state of the workload on a
	// worker to object storage, and then completely the worker to a blank state
	// (back to "available" state.)
	Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	// Restore restores a workload from checkpoint onto a worker.
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
	// UploadPausedCheckpoint copies a local (pause) checkpoint from this node's
	// disk to object storage. Unlike Checkpoint it drives no worker: the actor is
	// paused, its sandbox is gone; the checkpoint files plus their manifest
	// already sit under the actor's local-checkpoints directory.
	UploadPausedCheckpoint(context.Context, *UploadPausedCheckpointRequest) (*UploadPausedCheckpointResponse, error)
	// Terminate tells atelet to terminate/kill any running workload for an actor,
	// unmount its volumes, and clean up actor state on the node.
	Terminate(context.Context, *TerminateRequest) (*TerminateResponse, error)
	mustEmbedUnimplementedAteletServer()
}

// UnimplementedAteletServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAteletServer struct{}

func (UnimplementedAteletServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedAteletServer) Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedAteletServer) Restore(context.Context, *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedAteletServer) UploadPausedCheckpoint(context.Context, *UploadPausedCheckpointRequest) (*UploadPausedCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadPausedCheckpoint not implemented")
}
func (UnimplementedAteletServer) Terminate(context.Context, *TerminateRequest) (*TerminateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Terminate not implemented")
}
func (UnimplementedAteletServer) mustEmbedUnimplementedAteletServer() {}
func (UnimplementedAteletServer) testEmbeddedByValue()                {}

// UnsafeAteletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AteletServer will
// result in compilation errors.
type UnsafeAteletServer interface {
	mustEmbedUnimplementedAteletServer()
}

func RegisterAteletServer(s grpc.ServiceRegistrar, srv AteletServer) {
	// If the following call panics, it indicates UnimplementedAteletServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Atelet_ServiceDesc, srv)
}

func _Atelet_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteletServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Atelet_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteletServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Atelet_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteletServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Atelet_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteletServer).Checkpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Atelet_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteletServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Atelet_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteletServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Atelet_UploadPausedCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPausedCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteletServer).UploadPausedCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Atelet_UploadPausedCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteletServer).UploadPausedCheckpoint(ctx, req.(*UploadPausedCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Atelet_Terminate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteletServer).Terminate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Atelet_Terminate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteletServer).Terminate(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Atelet_ServiceDesc is the grpc.ServiceDesc for Atelet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Atelet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atelet.Atelet",
	HandlerType: (*AteletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Atelet_Run_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _Atelet_Checkpoint_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _Atelet_Restore_Handler,
		},
		{
			MethodName: "UploadPausedCheckpoint",
			Handler:    _Atelet_UploadPausedCheckpoint_Handler,
		},
		{
			MethodName: "Terminate",
			Handler:    _Atelet_Terminate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atelet.proto",
}
