// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: hostruntime.proto

package hostruntimepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivateRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ActorUid            string                 `protobuf:"bytes,1,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	Image               string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	CpuMilli            int64                  `protobuf:"varint,3,opt,name=cpu_milli,json=cpuMilli,proto3" json:"cpu_milli,omitempty"`
	MemoryBytes         int64                  `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	ReadinessProbe      *HTTPReadinessProbe    `protobuf:"bytes,5,opt,name=readiness_probe,json=readinessProbe,proto3" json:"readiness_probe,omitempty"`
	ExternalSnapshotUri *string                `protobuf:"bytes,6,opt,name=external_snapshot_uri,json=externalSnapshotUri,proto3,oneof" json:"external_snapshot_uri,omitempty"`
	LocalSnapshotName   *string                `protobuf:"bytes,7,opt,name=local_snapshot_name,json=localSnapshotName,proto3,oneof" json:"local_snapshot_name,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	mi := &file_hostruntime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{0}
}

func (x *ActivateRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *ActivateRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ActivateRequest) GetCpuMilli() int64 {
	if x != nil {
		return x.CpuMilli
	}
	return 0
}

func (x *ActivateRequest) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ActivateRequest) GetReadinessProbe() *HTTPReadinessProbe {
	if x != nil {
		return x.ReadinessProbe
	}
	return nil
}

func (x *ActivateRequest) GetExternalSnapshotUri() string {
	if x != nil && x.ExternalSnapshotUri != nil {
		return *x.ExternalSnapshotUri
	}
	return ""
}

func (x *ActivateRequest) GetLocalSnapshotName() string {
	if x != nil && x.LocalSnapshotName != nil {
		return *x.LocalSnapshotName
	}
	return ""
}

type PauseRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActorUid          string                 `protobuf:"bytes,1,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	LocalSnapshotName string                 `protobuf:"bytes,2,opt,name=local_snapshot_name,json=localSnapshotName,proto3" json:"local_snapshot_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PauseRequest) Reset() {
	*x = PauseRequest{}
	mi := &file_hostruntime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRequest) ProtoMessage() {}

func (x *PauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRequest.ProtoReflect.Descriptor instead.
func (*PauseRequest) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{1}
}

func (x *PauseRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *PauseRequest) GetLocalSnapshotName() string {
	if x != nil {
		return x.LocalSnapshotName
	}
	return ""
}

type PauseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseResponse) Reset() {
	*x = PauseResponse{}
	mi := &file_hostruntime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseResponse) ProtoMessage() {}

func (x *PauseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseResponse.ProtoReflect.Descriptor instead.
func (*PauseResponse) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{2}
}

type CheckpointRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ActorUid            string                 `protobuf:"bytes,1,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	ExternalSnapshotUri string                 `protobuf:"bytes,2,opt,name=external_snapshot_uri,json=externalSnapshotUri,proto3" json:"external_snapshot_uri,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_hostruntime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{3}
}

func (x *CheckpointRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *CheckpointRequest) GetExternalSnapshotUri() string {
	if x != nil {
		return x.ExternalSnapshotUri
	}
	return ""
}

type CheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_hostruntime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{4}
}

type DiscardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUid      string                 `protobuf:"bytes,1,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscardRequest) Reset() {
	*x = DiscardRequest{}
	mi := &file_hostruntime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardRequest) ProtoMessage() {}

func (x *DiscardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardRequest.ProtoReflect.Descriptor instead.
func (*DiscardRequest) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{5}
}

func (x *DiscardRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

type DiscardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscardResponse) Reset() {
	*x = DiscardResponse{}
	mi := &file_hostruntime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardResponse) ProtoMessage() {}

func (x *DiscardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardResponse.ProtoReflect.Descriptor instead.
func (*DiscardResponse) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{6}
}

type HTTPReadinessProbe struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Port           int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Path           string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HTTPReadinessProbe) Reset() {
	*x = HTTPReadinessProbe{}
	mi := &file_hostruntime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPReadinessProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPReadinessProbe) ProtoMessage() {}

func (x *HTTPReadinessProbe) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPReadinessProbe.ProtoReflect.Descriptor instead.
func (*HTTPReadinessProbe) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{7}
}

func (x *HTTPReadinessProbe) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HTTPReadinessProbe) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPReadinessProbe) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ActivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *ActorEndpoint         `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateResponse) Reset() {
	*x = ActivateResponse{}
	mi := &file_hostruntime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateResponse) ProtoMessage() {}

func (x *ActivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateResponse.ProtoReflect.Descriptor instead.
func (*ActivateResponse) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{8}
}

func (x *ActivateResponse) GetEndpoint() *ActorEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type ActorEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorEndpoint) Reset() {
	*x = ActorEndpoint{}
	mi := &file_hostruntime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorEndpoint) ProtoMessage() {}

func (x *ActorEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorEndpoint.ProtoReflect.Descriptor instead.
func (*ActorEndpoint) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{9}
}

func (x *ActorEndpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ActorEndpoint) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type TerminateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUid      string                 `protobuf:"bytes,1,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	mi := &file_hostruntime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{10}
}

func (x *TerminateRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

type TerminateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateResponse) Reset() {
	*x = TerminateResponse{}
	mi := &file_hostruntime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateResponse) ProtoMessage() {}

func (x *TerminateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateResponse.ProtoReflect.Descriptor instead.
func (*TerminateResponse) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{11}
}

var File_hostruntime_proto protoreflect.FileDescriptor

const file_hostruntime_proto_rawDesc = "" +
	"\n" +
	"\x11hostruntime.proto\x12\vhostruntime\"\xee\x02\n" +
	"\x0fActivateRequest\x12\x1b\n" +
	"\tactor_uid\x18\x01 \x01(\tR\bactorUid\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1b\n" +
	"\tcpu_milli\x18\x03 \x01(\x03R\bcpuMilli\x12!\n" +
	"\fmemory_bytes\x18\x04 \x01(\x03R\vmemoryBytes\x12H\n" +
	"\x0freadiness_probe\x18\x05 \x01(\v2\x1f.hostruntime.HTTPReadinessProbeR\x0ereadinessProbe\x127\n" +
	"\x15external_snapshot_uri\x18\x06 \x01(\tH\x00R\x13externalSnapshotUri\x88\x01\x01\x123\n" +
	"\x13local_snapshot_name\x18\a \x01(\tH\x01R\x11localSnapshotName\x88\x01\x01B\x18\n" +
	"\x16_external_snapshot_uriB\x16\n" +
	"\x14_local_snapshot_name\"[\n" +
	"\fPauseRequest\x12\x1b\n" +
	"\tactor_uid\x18\x01 \x01(\tR\bactorUid\x12.\n" +
	"\x13local_snapshot_name\x18\x02 \x01(\tR\x11localSnapshotName\"\x0f\n" +
	"\rPauseResponse\"d\n" +
	"\x11CheckpointRequest\x12\x1b\n" +
	"\tactor_uid\x18\x01 \x01(\tR\bactorUid\x122\n" +
	"\x15external_snapshot_uri\x18\x02 \x01(\tR\x13externalSnapshotUri\"\x14\n" +
	"\x12CheckpointResponse\"-\n" +
	"\x0eDiscardRequest\x12\x1b\n" +
	"\tactor_uid\x18\x01 \x01(\tR\bactorUid\"\x11\n" +
	"\x0fDiscardResponse\"e\n" +
	"\x12HTTPReadinessProbe\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"J\n" +
	"\x10ActivateResponse\x126\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1a.hostruntime.ActorEndpointR\bendpoint\"7\n" +
	"\rActorEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"/\n" +
	"\x10TerminateRequest\x12\x1b\n" +
	"\tactor_uid\x18\x01 \x01(\tR\bactorUid\"\x13\n" +
	"\x11TerminateResponse2\x81\x03\n" +
	"\vHostRuntime\x12I\n" +
	"\bActivate\x12\x1c.hostruntime.ActivateRequest\x1a\x1d.hostruntime.ActivateResponse\"\x00\x12@\n" +
	"\x05Pause\x12\x19.hostruntime.PauseRequest\x1a\x1a.hostruntime.PauseResponse\"\x00\x12O\n" +
	"\n" +
	"Checkpoint\x12\x1e.hostruntime.CheckpointRequest\x1a\x1f.hostruntime.CheckpointResponse\"\x00\x12F\n" +
	"\aDiscard\x12\x1b.hostruntime.DiscardRequest\x1a\x1c.hostruntime.DiscardResponse\"\x00\x12L\n" +
	"\tTerminate\x12\x1d.hostruntime.TerminateRequest\x1a\x1e.hostruntime.TerminateResponse\"\x00B>Z<github.com/agent-substrate/substrate/pkg/proto/hostruntimepbb\x06proto3"

var (
	file_hostruntime_proto_rawDescOnce sync.Once
	file_hostruntime_proto_rawDescData []byte
)

func file_hostruntime_proto_rawDescGZIP() []byte {
	file_hostruntime_proto_rawDescOnce.Do(func() {
		file_hostruntime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hostruntime_proto_rawDesc), len(file_hostruntime_proto_rawDesc)))
	})
	return file_hostruntime_proto_rawDescData
}

var file_hostruntime_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_hostruntime_proto_goTypes = []any{
	(*ActivateRequest)(nil),    // 0: hostruntime.ActivateRequest
	(*PauseRequest)(nil),       // 1: hostruntime.PauseRequest
	(*PauseResponse)(nil),      // 2: hostruntime.PauseResponse
	(*CheckpointRequest)(nil),  // 3: hostruntime.CheckpointRequest
	(*CheckpointResponse)(nil), // 4: hostruntime.CheckpointResponse
	(*DiscardRequest)(nil),     // 5: hostruntime.DiscardRequest
	(*DiscardResponse)(nil),    // 6: hostruntime.DiscardResponse
	(*HTTPReadinessProbe)(nil), // 7: hostruntime.HTTPReadinessProbe
	(*ActivateResponse)(nil),   // 8: hostruntime.ActivateResponse
	(*ActorEndpoint)(nil),      // 9: hostruntime.ActorEndpoint
	(*TerminateRequest)(nil),   // 10: hostruntime.TerminateRequest
	(*TerminateResponse)(nil),  // 11: hostruntime.TerminateResponse
}
var file_hostruntime_proto_depIdxs = []int32{
	7,  // 0: hostruntime.ActivateRequest.readiness_probe:type_name -> hostruntime.HTTPReadinessProbe
	9,  // 1: hostruntime.ActivateResponse.endpoint:type_name -> hostruntime.ActorEndpoint
	0,  // 2: hostruntime.HostRuntime.Activate:input_type -> hostruntime.ActivateRequest
	1,  // 3: hostruntime.HostRuntime.Pause:input_type -> hostruntime.PauseRequest
	3,  // 4: hostruntime.HostRuntime.Checkpoint:input_type -> hostruntime.CheckpointRequest
	5,  // 5: hostruntime.HostRuntime.Discard:input_type -> hostruntime.DiscardRequest
	10, // 6: hostruntime.HostRuntime.Terminate:input_type -> hostruntime.TerminateRequest
	8,  // 7: hostruntime.HostRuntime.Activate:output_type -> hostruntime.ActivateResponse
	2,  // 8: hostruntime.HostRuntime.Pause:output_type -> hostruntime.PauseResponse
	4,  // 9: hostruntime.HostRuntime.Checkpoint:output_type -> hostruntime.CheckpointResponse
	6,  // 10: hostruntime.HostRuntime.Discard:output_type -> hostruntime.DiscardResponse
	11, // 11: hostruntime.HostRuntime.Terminate:output_type -> hostruntime.TerminateResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_hostruntime_proto_init() }
func file_hostruntime_proto_init() {
	if File_hostruntime_proto != nil {
		return
	}
	file_hostruntime_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hostruntime_proto_rawDesc), len(file_hostruntime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hostruntime_proto_goTypes,
		DependencyIndexes: file_hostruntime_proto_depIdxs,
		MessageInfos:      file_hostruntime_proto_msgTypes,
	}.Build()
	File_hostruntime_proto = out.File
	file_hostruntime_proto_goTypes = nil
	file_hostruntime_proto_depIdxs = nil
}
