// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: hostruntime.proto

package hostruntimepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActorUid       string                 `protobuf:"bytes,1,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	Image          string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	CpuMilli       int64                  `protobuf:"varint,3,opt,name=cpu_milli,json=cpuMilli,proto3" json:"cpu_milli,omitempty"`
	MemoryBytes    int64                  `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	ReadinessProbe *HTTPReadinessProbe    `protobuf:"bytes,5,opt,name=readiness_probe,json=readinessProbe,proto3" json:"readiness_probe,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	mi := &file_hostruntime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{0}
}

func (x *ActivateRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *ActivateRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ActivateRequest) GetCpuMilli() int64 {
	if x != nil {
		return x.CpuMilli
	}
	return 0
}

func (x *ActivateRequest) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ActivateRequest) GetReadinessProbe() *HTTPReadinessProbe {
	if x != nil {
		return x.ReadinessProbe
	}
	return nil
}

type HTTPReadinessProbe struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Port           int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Path           string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HTTPReadinessProbe) Reset() {
	*x = HTTPReadinessProbe{}
	mi := &file_hostruntime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPReadinessProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPReadinessProbe) ProtoMessage() {}

func (x *HTTPReadinessProbe) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPReadinessProbe.ProtoReflect.Descriptor instead.
func (*HTTPReadinessProbe) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{1}
}

func (x *HTTPReadinessProbe) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HTTPReadinessProbe) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPReadinessProbe) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ActivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *ActorEndpoint         `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateResponse) Reset() {
	*x = ActivateResponse{}
	mi := &file_hostruntime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateResponse) ProtoMessage() {}

func (x *ActivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateResponse.ProtoReflect.Descriptor instead.
func (*ActivateResponse) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{2}
}

func (x *ActivateResponse) GetEndpoint() *ActorEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type ActorEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorEndpoint) Reset() {
	*x = ActorEndpoint{}
	mi := &file_hostruntime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorEndpoint) ProtoMessage() {}

func (x *ActorEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorEndpoint.ProtoReflect.Descriptor instead.
func (*ActorEndpoint) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{3}
}

func (x *ActorEndpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ActorEndpoint) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type TerminateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUid      string                 `protobuf:"bytes,1,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	mi := &file_hostruntime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{4}
}

func (x *TerminateRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

type TerminateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateResponse) Reset() {
	*x = TerminateResponse{}
	mi := &file_hostruntime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateResponse) ProtoMessage() {}

func (x *TerminateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostruntime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateResponse.ProtoReflect.Descriptor instead.
func (*TerminateResponse) Descriptor() ([]byte, []int) {
	return file_hostruntime_proto_rawDescGZIP(), []int{5}
}

var File_hostruntime_proto protoreflect.FileDescriptor

const file_hostruntime_proto_rawDesc = "" +
	"\n" +
	"\x11hostruntime.proto\x12\vhostruntime\"\xce\x01\n" +
	"\x0fActivateRequest\x12\x1b\n" +
	"\tactor_uid\x18\x01 \x01(\tR\bactorUid\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1b\n" +
	"\tcpu_milli\x18\x03 \x01(\x03R\bcpuMilli\x12!\n" +
	"\fmemory_bytes\x18\x04 \x01(\x03R\vmemoryBytes\x12H\n" +
	"\x0freadiness_probe\x18\x05 \x01(\v2\x1f.hostruntime.HTTPReadinessProbeR\x0ereadinessProbe\"e\n" +
	"\x12HTTPReadinessProbe\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"J\n" +
	"\x10ActivateResponse\x126\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1a.hostruntime.ActorEndpointR\bendpoint\"7\n" +
	"\rActorEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"/\n" +
	"\x10TerminateRequest\x12\x1b\n" +
	"\tactor_uid\x18\x01 \x01(\tR\bactorUid\"\x13\n" +
	"\x11TerminateResponse2\xa6\x01\n" +
	"\vHostRuntime\x12I\n" +
	"\bActivate\x12\x1c.hostruntime.ActivateRequest\x1a\x1d.hostruntime.ActivateResponse\"\x00\x12L\n" +
	"\tTerminate\x12\x1d.hostruntime.TerminateRequest\x1a\x1e.hostruntime.TerminateResponse\"\x00B>Z<github.com/agent-substrate/substrate/pkg/proto/hostruntimepbb\x06proto3"

var (
	file_hostruntime_proto_rawDescOnce sync.Once
	file_hostruntime_proto_rawDescData []byte
)

func file_hostruntime_proto_rawDescGZIP() []byte {
	file_hostruntime_proto_rawDescOnce.Do(func() {
		file_hostruntime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hostruntime_proto_rawDesc), len(file_hostruntime_proto_rawDesc)))
	})
	return file_hostruntime_proto_rawDescData
}

var file_hostruntime_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_hostruntime_proto_goTypes = []any{
	(*ActivateRequest)(nil),    // 0: hostruntime.ActivateRequest
	(*HTTPReadinessProbe)(nil), // 1: hostruntime.HTTPReadinessProbe
	(*ActivateResponse)(nil),   // 2: hostruntime.ActivateResponse
	(*ActorEndpoint)(nil),      // 3: hostruntime.ActorEndpoint
	(*TerminateRequest)(nil),   // 4: hostruntime.TerminateRequest
	(*TerminateResponse)(nil),  // 5: hostruntime.TerminateResponse
}
var file_hostruntime_proto_depIdxs = []int32{
	1, // 0: hostruntime.ActivateRequest.readiness_probe:type_name -> hostruntime.HTTPReadinessProbe
	3, // 1: hostruntime.ActivateResponse.endpoint:type_name -> hostruntime.ActorEndpoint
	0, // 2: hostruntime.HostRuntime.Activate:input_type -> hostruntime.ActivateRequest
	4, // 3: hostruntime.HostRuntime.Terminate:input_type -> hostruntime.TerminateRequest
	2, // 4: hostruntime.HostRuntime.Activate:output_type -> hostruntime.ActivateResponse
	5, // 5: hostruntime.HostRuntime.Terminate:output_type -> hostruntime.TerminateResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hostruntime_proto_init() }
func file_hostruntime_proto_init() {
	if File_hostruntime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hostruntime_proto_rawDesc), len(file_hostruntime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hostruntime_proto_goTypes,
		DependencyIndexes: file_hostruntime_proto_depIdxs,
		MessageInfos:      file_hostruntime_proto_msgTypes,
	}.Build()
	File_hostruntime_proto = out.File
	file_hostruntime_proto_goTypes = nil
	file_hostruntime_proto_depIdxs = nil
}
