// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: hostruntime.proto

package hostruntimepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostRuntime_Activate_FullMethodName  = "/hostruntime.HostRuntime/Activate"
	HostRuntime_Terminate_FullMethodName = "/hostruntime.HostRuntime/Terminate"
)

// HostRuntimeClient is the client API for HostRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostRuntime manages Actors on a provider host. Requests are idempotent by
// actor_uid: retrying Activate returns the same running Actor, and retrying
// Terminate after cleanup succeeds.
type HostRuntimeClient interface {
	Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error)
	Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error)
}

type hostRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewHostRuntimeClient(cc grpc.ClientConnInterface) HostRuntimeClient {
	return &hostRuntimeClient{cc}
}

func (c *hostRuntimeClient) Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateResponse)
	err := c.cc.Invoke(ctx, HostRuntime_Activate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostRuntimeClient) Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateResponse)
	err := c.cc.Invoke(ctx, HostRuntime_Terminate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostRuntimeServer is the server API for HostRuntime service.
// All implementations must embed UnimplementedHostRuntimeServer
// for forward compatibility.
//
// HostRuntime manages Actors on a provider host. Requests are idempotent by
// actor_uid: retrying Activate returns the same running Actor, and retrying
// Terminate after cleanup succeeds.
type HostRuntimeServer interface {
	Activate(context.Context, *ActivateRequest) (*ActivateResponse, error)
	Terminate(context.Context, *TerminateRequest) (*TerminateResponse, error)
	mustEmbedUnimplementedHostRuntimeServer()
}

// UnimplementedHostRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostRuntimeServer struct{}

func (UnimplementedHostRuntimeServer) Activate(context.Context, *ActivateRequest) (*ActivateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Activate not implemented")
}
func (UnimplementedHostRuntimeServer) Terminate(context.Context, *TerminateRequest) (*TerminateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Terminate not implemented")
}
func (UnimplementedHostRuntimeServer) mustEmbedUnimplementedHostRuntimeServer() {}
func (UnimplementedHostRuntimeServer) testEmbeddedByValue()                     {}

// UnsafeHostRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostRuntimeServer will
// result in compilation errors.
type UnsafeHostRuntimeServer interface {
	mustEmbedUnimplementedHostRuntimeServer()
}

func RegisterHostRuntimeServer(s grpc.ServiceRegistrar, srv HostRuntimeServer) {
	// If the following call panics, it indicates UnimplementedHostRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostRuntime_ServiceDesc, srv)
}

func _HostRuntime_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostRuntimeServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostRuntime_Activate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostRuntimeServer).Activate(ctx, req.(*ActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostRuntime_Terminate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostRuntimeServer).Terminate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostRuntime_Terminate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostRuntimeServer).Terminate(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostRuntime_ServiceDesc is the grpc.ServiceDesc for HostRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hostruntime.HostRuntime",
	HandlerType: (*HostRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Activate",
			Handler:    _HostRuntime_Activate_Handler,
		},
		{
			MethodName: "Terminate",
			Handler:    _HostRuntime_Terminate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hostruntime.proto",
}
