//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by validation-gen. DO NOT EDIT.

package ateapipb

import (
	context "context"

	equality "k8s.io/apimachinery/pkg/api/equality"
	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
)

// Validate_ActorRef validates an instance of ActorRef according
// to declarative validation rules in the API schema.
func Validate_ActorRef(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *ActorRef) (errs field.ErrorList) {

	{ // field ActorRef.Atespace
		fn := func(
			fldPath *field.Path,
			obj, oldObj *string,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			if e := validate.ShortName(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *ActorRef) *string {
				return &oldObj.Atespace
			})
		errs = append(errs, fn(fldPath.Child("atespace"), &obj.Atespace, oldVal, oldObj != nil)...)
	}

	{ // field ActorRef.Name
		fn := func(
			fldPath *field.Path,
			obj, oldObj *string,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			if e := validate.ShortName(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *ActorRef) *string {
				return &oldObj.Name
			})
		errs = append(errs, fn(fldPath.Child("name"), &obj.Name, oldVal, oldObj != nil)...)
	}

	return errs
}

// Validate_Assignment validates an instance of Assignment according
// to declarative validation rules in the API schema.
func Validate_Assignment(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *Assignment) (errs field.ErrorList) {

	{ // field Assignment.ActorTemplate
		fn := func(
			fldPath *field.Path,
			obj, oldObj *KubeNamespacedObjectRef,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *Assignment) *KubeNamespacedObjectRef {
				return oldObj.ActorTemplate
			})
		errs = append(errs, fn(fldPath.Child("actor_template"), obj.ActorTemplate, oldVal, oldObj != nil)...)
	}

	{ // field Assignment.Actor
		fn := func(
			fldPath *field.Path,
			obj, oldObj *ActorRef,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			// call the type's validation function
			errs = append(errs, Validate_ActorRef(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *Assignment) *ActorRef {
				return oldObj.Actor
			})
		errs = append(errs, fn(fldPath.Child("actor"), obj.Actor, oldVal, oldObj != nil)...)
	}

	return errs
}

// Validate_CreateActorRequest validates an instance of CreateActorRequest according
// to declarative validation rules in the API schema.
func Validate_CreateActorRequest(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *CreateActorRequest) (errs field.ErrorList) {

	{ // field CreateActorRequest.ActorRef
		fn := func(
			fldPath *field.Path,
			obj, oldObj *ActorRef,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			// call the type's validation function
			errs = append(errs, Validate_ActorRef(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *CreateActorRequest) *ActorRef {
				return oldObj.ActorRef
			})
		errs = append(errs, fn(fldPath.Child("actor_ref"), obj.ActorRef, oldVal, oldObj != nil)...)
	}

	{ // field CreateActorRequest.ActorTemplateNamespace
		fn := func(
			fldPath *field.Path,
			obj, oldObj *string,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			if e := validate.ShortName(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *CreateActorRequest) *string {
				return &oldObj.ActorTemplateNamespace
			})
		errs = append(errs, fn(fldPath.Child("actor_template_namespace"), &obj.ActorTemplateNamespace, oldVal, oldObj != nil)...)
	}

	{ // field CreateActorRequest.ActorTemplateName
		fn := func(
			fldPath *field.Path,
			obj, oldObj *string,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			if e := validate.LongName(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *CreateActorRequest) *string {
				return &oldObj.ActorTemplateName
			})
		errs = append(errs, fn(fldPath.Child("actor_template_name"), &obj.ActorTemplateName, oldVal, oldObj != nil)...)
	}

	{ // field CreateActorRequest.WorkerSelector
		fn := func(
			fldPath *field.Path,
			obj, oldObj *Selector,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.OptionalPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			// call the type's validation function
			errs = append(errs, Validate_Selector(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *CreateActorRequest) *Selector {
				return oldObj.WorkerSelector
			})
		errs = append(errs, fn(fldPath.Child("worker_selector"), obj.WorkerSelector, oldVal, oldObj != nil)...)
	}

	return errs
}

// Validate_DeleteActorRequest validates an instance of DeleteActorRequest according
// to declarative validation rules in the API schema.
func Validate_DeleteActorRequest(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *DeleteActorRequest) (errs field.ErrorList) {

	{ // field DeleteActorRequest.ActorRef
		fn := func(
			fldPath *field.Path,
			obj, oldObj *ActorRef,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			// call the type's validation function
			errs = append(errs, Validate_ActorRef(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *DeleteActorRequest) *ActorRef {
				return oldObj.ActorRef
			})
		errs = append(errs, fn(fldPath.Child("actor_ref"), obj.ActorRef, oldVal, oldObj != nil)...)
	}

	return errs
}

// Validate_GetActorRequest validates an instance of GetActorRequest according
// to declarative validation rules in the API schema.
func Validate_GetActorRequest(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *GetActorRequest) (errs field.ErrorList) {

	{ // field GetActorRequest.ActorRef
		fn := func(
			fldPath *field.Path,
			obj, oldObj *ActorRef,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			// call the type's validation function
			errs = append(errs, Validate_ActorRef(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *GetActorRequest) *ActorRef {
				return oldObj.ActorRef
			})
		errs = append(errs, fn(fldPath.Child("actor_ref"), obj.ActorRef, oldVal, oldObj != nil)...)
	}

	return errs
}

// Validate_PauseActorRequest validates an instance of PauseActorRequest according
// to declarative validation rules in the API schema.
func Validate_PauseActorRequest(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *PauseActorRequest) (errs field.ErrorList) {

	{ // field PauseActorRequest.ActorRef
		fn := func(
			fldPath *field.Path,
			obj, oldObj *ActorRef,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			// call the type's validation function
			errs = append(errs, Validate_ActorRef(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *PauseActorRequest) *ActorRef {
				return oldObj.ActorRef
			})
		errs = append(errs, fn(fldPath.Child("actor_ref"), obj.ActorRef, oldVal, oldObj != nil)...)
	}

	return errs
}

// Validate_ResumeActorRequest validates an instance of ResumeActorRequest according
// to declarative validation rules in the API schema.
func Validate_ResumeActorRequest(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *ResumeActorRequest) (errs field.ErrorList) {

	{ // field ResumeActorRequest.ActorRef
		fn := func(
			fldPath *field.Path,
			obj, oldObj *ActorRef,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			// call the type's validation function
			errs = append(errs, Validate_ActorRef(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *ResumeActorRequest) *ActorRef {
				return oldObj.ActorRef
			})
		errs = append(errs, fn(fldPath.Child("actor_ref"), obj.ActorRef, oldVal, oldObj != nil)...)
	}

	// field ResumeActorRequest.Boot has no validation
	return errs
}

// Validate_Selector validates an instance of Selector according
// to declarative validation rules in the API schema.
func Validate_Selector(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *Selector) (errs field.ErrorList) {

	{ // field Selector.MatchLabels
		fn := func(
			fldPath *field.Path,
			obj, oldObj map[string]string,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			/* not public yet
			if e := validate.MaxProperties(ctx, op, fldPath, obj, oldObj, 10); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			*/
			if e := validate.OptionalMap(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			if e := validate.EachMapKey(ctx, op, fldPath, obj, oldObj, validate.LabelKey).MarkAlpha(); len(e) != 0 {
				errs = append(errs, e...)
			}
			if e := validate.EachMapVal(ctx, op, fldPath, obj, oldObj, validate.DirectEqual, validate.LabelValue).MarkAlpha(); len(e) != 0 {
				errs = append(errs, e...)
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *Selector) map[string]string {
				return oldObj.MatchLabels
			})
		errs = append(errs, fn(fldPath.Child("match_labels"), obj.MatchLabels, oldVal, oldObj != nil)...)
	}

	return errs
}

// Validate_SuspendActorRequest validates an instance of SuspendActorRequest according
// to declarative validation rules in the API schema.
func Validate_SuspendActorRequest(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *SuspendActorRequest) (errs field.ErrorList) {

	{ // field SuspendActorRequest.ActorRef
		fn := func(
			fldPath *field.Path,
			obj, oldObj *ActorRef,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			// call the type's validation function
			errs = append(errs, Validate_ActorRef(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *SuspendActorRequest) *ActorRef {
				return oldObj.ActorRef
			})
		errs = append(errs, fn(fldPath.Child("actor_ref"), obj.ActorRef, oldVal, oldObj != nil)...)
	}

	return errs
}

// Validate_UpdateActorRequest validates an instance of UpdateActorRequest according
// to declarative validation rules in the API schema.
func Validate_UpdateActorRequest(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *UpdateActorRequest) (errs field.ErrorList) {

	{ // field UpdateActorRequest.ActorRef
		fn := func(
			fldPath *field.Path,
			obj, oldObj *ActorRef,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			// call the type's validation function
			errs = append(errs, Validate_ActorRef(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *UpdateActorRequest) *ActorRef {
				return oldObj.ActorRef
			})
		errs = append(errs, fn(fldPath.Child("actor_ref"), obj.ActorRef, oldVal, oldObj != nil)...)
	}

	{ // field UpdateActorRequest.WorkerSelector
		fn := func(
			fldPath *field.Path,
			obj, oldObj *Selector,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.OptionalPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			// call the type's validation function
			errs = append(errs, Validate_Selector(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *UpdateActorRequest) *Selector {
				return oldObj.WorkerSelector
			})
		errs = append(errs, fn(fldPath.Child("worker_selector"), obj.WorkerSelector, oldVal, oldObj != nil)...)
	}

	return errs
}

// Validate_Worker validates an instance of Worker according
// to declarative validation rules in the API schema.
func Validate_Worker(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *Worker) (errs field.ErrorList) {

	// field Worker.WorkerNamespace has no validation
	// field Worker.WorkerPool has no validation
	// field Worker.WorkerPod has no validation

	{ // field Worker.Assignment
		fn := func(
			fldPath *field.Path,
			obj, oldObj *Assignment,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.OptionalPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			// call the type's validation function
			errs = append(errs, Validate_Assignment(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *Worker) *Assignment {
				return oldObj.Assignment
			})
		errs = append(errs, fn(fldPath.Child("assignment"), obj.Assignment, oldVal, oldObj != nil)...)
	}

	// field Worker.Ip has no validation
	// field Worker.Version has no validation
	// field Worker.WorkerPodUid has no validation
	// field Worker.NodeName has no validation
	return errs
}
