// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package keychain contains proto definitions for gRPC communication with
// Google Riptide's gcfsd keychain service (unix:///run/gcfsd/keychain.sock).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: keychain.proto

package riptidekeychain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateCredsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container's Image field (e.g. imageID or imageDigest).
	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Authentication configuration for pulling the image.
	Auth          *AuthConfig `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCredsRequest) Reset() {
	*x = UpdateCredsRequest{}
	mi := &file_keychain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCredsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCredsRequest) ProtoMessage() {}

func (x *UpdateCredsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keychain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCredsRequest.ProtoReflect.Descriptor instead.
func (*UpdateCredsRequest) Descriptor() ([]byte, []int) {
	return file_keychain_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateCredsRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *UpdateCredsRequest) GetAuth() *AuthConfig {
	if x != nil {
		return x.Auth
	}
	return nil
}

type UpdateCredsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCredsResponse) Reset() {
	*x = UpdateCredsResponse{}
	mi := &file_keychain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCredsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCredsResponse) ProtoMessage() {}

func (x *UpdateCredsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keychain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCredsResponse.ProtoReflect.Descriptor instead.
func (*UpdateCredsResponse) Descriptor() ([]byte, []int) {
	return file_keychain_proto_rawDescGZIP(), []int{1}
}

// AuthConfig contains authorization information for connecting to a registry.
type AuthConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Auth          string                 `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	ServerAddress string                 `protobuf:"bytes,4,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	// IdentityToken is used to authenticate the user and get
	// an access token for the registry.
	IdentityToken string `protobuf:"bytes,5,opt,name=identity_token,json=identityToken,proto3" json:"identity_token,omitempty"`
	// RegistryToken is a bearer token to be sent to a registry.
	RegistryToken string `protobuf:"bytes,6,opt,name=registry_token,json=registryToken,proto3" json:"registry_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthConfig) Reset() {
	*x = AuthConfig{}
	mi := &file_keychain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConfig) ProtoMessage() {}

func (x *AuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_keychain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConfig.ProtoReflect.Descriptor instead.
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return file_keychain_proto_rawDescGZIP(), []int{2}
}

func (x *AuthConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthConfig) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *AuthConfig) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *AuthConfig) GetIdentityToken() string {
	if x != nil {
		return x.IdentityToken
	}
	return ""
}

func (x *AuthConfig) GetRegistryToken() string {
	if x != nil {
		return x.RegistryToken
	}
	return ""
}

type RemoveCredsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container's Image field (e.g. imageID or imageDigest).
	Image         string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCredsRequest) Reset() {
	*x = RemoveCredsRequest{}
	mi := &file_keychain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCredsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCredsRequest) ProtoMessage() {}

func (x *RemoveCredsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keychain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCredsRequest.ProtoReflect.Descriptor instead.
func (*RemoveCredsRequest) Descriptor() ([]byte, []int) {
	return file_keychain_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveCredsRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type RemoveCredsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCredsResponse) Reset() {
	*x = RemoveCredsResponse{}
	mi := &file_keychain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCredsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCredsResponse) ProtoMessage() {}

func (x *RemoveCredsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keychain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCredsResponse.ProtoReflect.Descriptor instead.
func (*RemoveCredsResponse) Descriptor() ([]byte, []int) {
	return file_keychain_proto_rawDescGZIP(), []int{4}
}

var File_keychain_proto protoreflect.FileDescriptor

const file_keychain_proto_rawDesc = "" +
	"\n" +
	"\x0ekeychain.proto\x12&cloud.containers.riptide.fuse.keychain\"r\n" +
	"\x12UpdateCredsRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12F\n" +
	"\x04auth\x18\x02 \x01(\v22.cloud.containers.riptide.fuse.keychain.AuthConfigR\x04auth\"\x15\n" +
	"\x13UpdateCredsResponse\"\xcd\x01\n" +
	"\n" +
	"AuthConfig\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04auth\x18\x03 \x01(\tR\x04auth\x12%\n" +
	"\x0eserver_address\x18\x04 \x01(\tR\rserverAddress\x12%\n" +
	"\x0eidentity_token\x18\x05 \x01(\tR\ridentityToken\x12%\n" +
	"\x0eregistry_token\x18\x06 \x01(\tR\rregistryToken\"*\n" +
	"\x12RemoveCredsRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\"\x15\n" +
	"\x13RemoveCredsResponse2\xa0\x02\n" +
	"\bKeychain\x12\x88\x01\n" +
	"\vUpdateCreds\x12:.cloud.containers.riptide.fuse.keychain.UpdateCredsRequest\x1a;.cloud.containers.riptide.fuse.keychain.UpdateCredsResponse\"\x00\x12\x88\x01\n" +
	"\vRemoveCreds\x12:.cloud.containers.riptide.fuse.keychain.RemoveCredsRequest\x1a;.cloud.containers.riptide.fuse.keychain.RemoveCredsResponse\"\x00BEZCgithub.com/agent-substrate/substrate/internal/proto/riptidekeychainb\x06proto3"

var (
	file_keychain_proto_rawDescOnce sync.Once
	file_keychain_proto_rawDescData []byte
)

func file_keychain_proto_rawDescGZIP() []byte {
	file_keychain_proto_rawDescOnce.Do(func() {
		file_keychain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keychain_proto_rawDesc), len(file_keychain_proto_rawDesc)))
	})
	return file_keychain_proto_rawDescData
}

var file_keychain_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_keychain_proto_goTypes = []any{
	(*UpdateCredsRequest)(nil),  // 0: cloud.containers.riptide.fuse.keychain.UpdateCredsRequest
	(*UpdateCredsResponse)(nil), // 1: cloud.containers.riptide.fuse.keychain.UpdateCredsResponse
	(*AuthConfig)(nil),          // 2: cloud.containers.riptide.fuse.keychain.AuthConfig
	(*RemoveCredsRequest)(nil),  // 3: cloud.containers.riptide.fuse.keychain.RemoveCredsRequest
	(*RemoveCredsResponse)(nil), // 4: cloud.containers.riptide.fuse.keychain.RemoveCredsResponse
}
var file_keychain_proto_depIdxs = []int32{
	2, // 0: cloud.containers.riptide.fuse.keychain.UpdateCredsRequest.auth:type_name -> cloud.containers.riptide.fuse.keychain.AuthConfig
	0, // 1: cloud.containers.riptide.fuse.keychain.Keychain.UpdateCreds:input_type -> cloud.containers.riptide.fuse.keychain.UpdateCredsRequest
	3, // 2: cloud.containers.riptide.fuse.keychain.Keychain.RemoveCreds:input_type -> cloud.containers.riptide.fuse.keychain.RemoveCredsRequest
	1, // 3: cloud.containers.riptide.fuse.keychain.Keychain.UpdateCreds:output_type -> cloud.containers.riptide.fuse.keychain.UpdateCredsResponse
	4, // 4: cloud.containers.riptide.fuse.keychain.Keychain.RemoveCreds:output_type -> cloud.containers.riptide.fuse.keychain.RemoveCredsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_keychain_proto_init() }
func file_keychain_proto_init() {
	if File_keychain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keychain_proto_rawDesc), len(file_keychain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keychain_proto_goTypes,
		DependencyIndexes: file_keychain_proto_depIdxs,
		MessageInfos:      file_keychain_proto_msgTypes,
	}.Build()
	File_keychain_proto = out.File
	file_keychain_proto_goTypes = nil
	file_keychain_proto_depIdxs = nil
}
