// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package keychain contains proto definitions for gRPC communication with
// Google Riptide's gcfsd keychain service (unix:///run/gcfsd/keychain.sock).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: keychain.proto

package riptidekeychain

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Keychain_UpdateCreds_FullMethodName = "/cloud.containers.riptide.fuse.keychain.Keychain/UpdateCreds"
	Keychain_RemoveCreds_FullMethodName = "/cloud.containers.riptide.fuse.keychain.Keychain/RemoveCreds"
)

// KeychainClient is the client API for Keychain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeychainClient interface {
	// Update credentials for an image.
	UpdateCreds(ctx context.Context, in *UpdateCredsRequest, opts ...grpc.CallOption) (*UpdateCredsResponse, error)
	// Remove credentials for an image.
	RemoveCreds(ctx context.Context, in *RemoveCredsRequest, opts ...grpc.CallOption) (*RemoveCredsResponse, error)
}

type keychainClient struct {
	cc grpc.ClientConnInterface
}

func NewKeychainClient(cc grpc.ClientConnInterface) KeychainClient {
	return &keychainClient{cc}
}

func (c *keychainClient) UpdateCreds(ctx context.Context, in *UpdateCredsRequest, opts ...grpc.CallOption) (*UpdateCredsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCredsResponse)
	err := c.cc.Invoke(ctx, Keychain_UpdateCreds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keychainClient) RemoveCreds(ctx context.Context, in *RemoveCredsRequest, opts ...grpc.CallOption) (*RemoveCredsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveCredsResponse)
	err := c.cc.Invoke(ctx, Keychain_RemoveCreds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeychainServer is the server API for Keychain service.
// All implementations must embed UnimplementedKeychainServer
// for forward compatibility.
type KeychainServer interface {
	// Update credentials for an image.
	UpdateCreds(context.Context, *UpdateCredsRequest) (*UpdateCredsResponse, error)
	// Remove credentials for an image.
	RemoveCreds(context.Context, *RemoveCredsRequest) (*RemoveCredsResponse, error)
	mustEmbedUnimplementedKeychainServer()
}

// UnimplementedKeychainServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeychainServer struct{}

func (UnimplementedKeychainServer) UpdateCreds(context.Context, *UpdateCredsRequest) (*UpdateCredsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCreds not implemented")
}
func (UnimplementedKeychainServer) RemoveCreds(context.Context, *RemoveCredsRequest) (*RemoveCredsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveCreds not implemented")
}
func (UnimplementedKeychainServer) mustEmbedUnimplementedKeychainServer() {}
func (UnimplementedKeychainServer) testEmbeddedByValue()                  {}

// UnsafeKeychainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeychainServer will
// result in compilation errors.
type UnsafeKeychainServer interface {
	mustEmbedUnimplementedKeychainServer()
}

func RegisterKeychainServer(s grpc.ServiceRegistrar, srv KeychainServer) {
	// If the following call panics, it indicates UnimplementedKeychainServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Keychain_ServiceDesc, srv)
}

func _Keychain_UpdateCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCredsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeychainServer).UpdateCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keychain_UpdateCreds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeychainServer).UpdateCreds(ctx, req.(*UpdateCredsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keychain_RemoveCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCredsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeychainServer).RemoveCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keychain_RemoveCreds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeychainServer).RemoveCreds(ctx, req.(*RemoveCredsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Keychain_ServiceDesc is the grpc.ServiceDesc for Keychain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Keychain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.containers.riptide.fuse.keychain.Keychain",
	HandlerType: (*KeychainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateCreds",
			Handler:    _Keychain_UpdateCreds_Handler,
		},
		{
			MethodName: "RemoveCreds",
			Handler:    _Keychain_RemoveCreds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keychain.proto",
}
