// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//
//Copyright The containerd Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: sandbox.proto

package sandbox

import (
	types "github.com/containerd/containerd/api/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRestoreMode int32

const (
	TaskRestoreMode_TASK_RESTORE_MODE_UNSPECIFIED TaskRestoreMode = 0
	TaskRestoreMode_TASK_RESTORE_MODE_VM_RESTORED TaskRestoreMode = 1
)

// Enum value maps for TaskRestoreMode.
var (
	TaskRestoreMode_name = map[int32]string{
		0: "TASK_RESTORE_MODE_UNSPECIFIED",
		1: "TASK_RESTORE_MODE_VM_RESTORED",
	}
	TaskRestoreMode_value = map[string]int32{
		"TASK_RESTORE_MODE_UNSPECIFIED": 0,
		"TASK_RESTORE_MODE_VM_RESTORED": 1,
	}
)

func (x TaskRestoreMode) Enum() *TaskRestoreMode {
	p := new(TaskRestoreMode)
	*p = x
	return p
}

func (x TaskRestoreMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskRestoreMode) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_proto_enumTypes[0].Descriptor()
}

func (TaskRestoreMode) Type() protoreflect.EnumType {
	return &file_sandbox_proto_enumTypes[0]
}

func (x TaskRestoreMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskRestoreMode.Descriptor instead.
func (TaskRestoreMode) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

type CreateSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	BundlePath    string                 `protobuf:"bytes,2,opt,name=bundle_path,json=bundlePath,proto3" json:"bundle_path,omitempty"`
	Rootfs        []*types.Mount         `protobuf:"bytes,3,rep,name=rootfs,proto3" json:"rootfs,omitempty"`
	Options       *anypb.Any             `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	NetnsPath     string                 `protobuf:"bytes,5,opt,name=netns_path,json=netnsPath,proto3" json:"netns_path,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateSandboxRequest) GetBundlePath() string {
	if x != nil {
		return x.BundlePath
	}
	return ""
}

func (x *CreateSandboxRequest) GetRootfs() []*types.Mount {
	if x != nil {
		return x.Rootfs
	}
	return nil
}

func (x *CreateSandboxRequest) GetOptions() *anypb.Any {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateSandboxRequest) GetNetnsPath() string {
	if x != nil {
		return x.NetnsPath
	}
	return ""
}

func (x *CreateSandboxRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type CreateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{1}
}

type StartSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSandboxRequest) Reset() {
	*x = StartSandboxRequest{}
	mi := &file_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSandboxRequest) ProtoMessage() {}

func (x *StartSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSandboxRequest.ProtoReflect.Descriptor instead.
func (*StartSandboxRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *StartSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type StartSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Spec          *anypb.Any             `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSandboxResponse) Reset() {
	*x = StartSandboxResponse{}
	mi := &file_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSandboxResponse) ProtoMessage() {}

func (x *StartSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSandboxResponse.ProtoReflect.Descriptor instead.
func (*StartSandboxResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *StartSandboxResponse) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StartSandboxResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StartSandboxResponse) GetSpec() *anypb.Any {
	if x != nil {
		return x.Spec
	}
	return nil
}

type PlatformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformRequest) Reset() {
	*x = PlatformRequest{}
	mi := &file_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformRequest) ProtoMessage() {}

func (x *PlatformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformRequest.ProtoReflect.Descriptor instead.
func (*PlatformRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *PlatformRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type PlatformResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      *types.Platform        `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformResponse) Reset() {
	*x = PlatformResponse{}
	mi := &file_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformResponse) ProtoMessage() {}

func (x *PlatformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformResponse.ProtoReflect.Descriptor instead.
func (*PlatformResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *PlatformResponse) GetPlatform() *types.Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

type StopSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TimeoutSecs   uint32                 `protobuf:"varint,2,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSandboxRequest) Reset() {
	*x = StopSandboxRequest{}
	mi := &file_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxRequest) ProtoMessage() {}

func (x *StopSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxRequest.ProtoReflect.Descriptor instead.
func (*StopSandboxRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *StopSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *StopSandboxRequest) GetTimeoutSecs() uint32 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

type StopSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSandboxResponse) Reset() {
	*x = StopSandboxResponse{}
	mi := &file_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxResponse) ProtoMessage() {}

func (x *StopSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxResponse.ProtoReflect.Descriptor instead.
func (*StopSandboxResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{7}
}

type UpdateSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Resources     *anypb.Any             `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSandboxRequest) Reset() {
	*x = UpdateSandboxRequest{}
	mi := &file_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSandboxRequest) ProtoMessage() {}

func (x *UpdateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSandboxRequest.ProtoReflect.Descriptor instead.
func (*UpdateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *UpdateSandboxRequest) GetResources() *anypb.Any {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *UpdateSandboxRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type WaitSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitSandboxRequest) Reset() {
	*x = WaitSandboxRequest{}
	mi := &file_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitSandboxRequest) ProtoMessage() {}

func (x *WaitSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitSandboxRequest.ProtoReflect.Descriptor instead.
func (*WaitSandboxRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{9}
}

func (x *WaitSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type WaitSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitStatus    uint32                 `protobuf:"varint,1,opt,name=exit_status,json=exitStatus,proto3" json:"exit_status,omitempty"`
	ExitedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=exited_at,json=exitedAt,proto3" json:"exited_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitSandboxResponse) Reset() {
	*x = WaitSandboxResponse{}
	mi := &file_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitSandboxResponse) ProtoMessage() {}

func (x *WaitSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitSandboxResponse.ProtoReflect.Descriptor instead.
func (*WaitSandboxResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *WaitSandboxResponse) GetExitStatus() uint32 {
	if x != nil {
		return x.ExitStatus
	}
	return 0
}

func (x *WaitSandboxResponse) GetExitedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExitedAt
	}
	return nil
}

type UpdateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSandboxResponse) Reset() {
	*x = UpdateSandboxResponse{}
	mi := &file_sandbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSandboxResponse) ProtoMessage() {}

func (x *UpdateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSandboxResponse.ProtoReflect.Descriptor instead.
func (*UpdateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{11}
}

type SandboxStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Verbose       bool                   `protobuf:"varint,2,opt,name=verbose,proto3" json:"verbose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxStatusRequest) Reset() {
	*x = SandboxStatusRequest{}
	mi := &file_sandbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStatusRequest) ProtoMessage() {}

func (x *SandboxStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxStatusRequest.ProtoReflect.Descriptor instead.
func (*SandboxStatusRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{12}
}

func (x *SandboxStatusRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxStatusRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

type SandboxStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Info          map[string]string      `protobuf:"bytes,4,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExitedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=exited_at,json=exitedAt,proto3" json:"exited_at,omitempty"`
	Extra         *anypb.Any             `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxStatusResponse) Reset() {
	*x = SandboxStatusResponse{}
	mi := &file_sandbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStatusResponse) ProtoMessage() {}

func (x *SandboxStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxStatusResponse.ProtoReflect.Descriptor instead.
func (*SandboxStatusResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{13}
}

func (x *SandboxStatusResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxStatusResponse) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SandboxStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SandboxStatusResponse) GetInfo() map[string]string {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *SandboxStatusResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SandboxStatusResponse) GetExitedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExitedAt
	}
	return nil
}

func (x *SandboxStatusResponse) GetExtra() *anypb.Any {
	if x != nil {
		return x.Extra
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_sandbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{14}
}

func (x *PingRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_sandbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{15}
}

type ShutdownSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownSandboxRequest) Reset() {
	*x = ShutdownSandboxRequest{}
	mi := &file_sandbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownSandboxRequest) ProtoMessage() {}

func (x *ShutdownSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownSandboxRequest.ProtoReflect.Descriptor instead.
func (*ShutdownSandboxRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{16}
}

func (x *ShutdownSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type ShutdownSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownSandboxResponse) Reset() {
	*x = ShutdownSandboxResponse{}
	mi := &file_sandbox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownSandboxResponse) ProtoMessage() {}

func (x *ShutdownSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownSandboxResponse.ProtoReflect.Descriptor instead.
func (*ShutdownSandboxResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{17}
}

type SandboxMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxMetricsRequest) Reset() {
	*x = SandboxMetricsRequest{}
	mi := &file_sandbox_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxMetricsRequest) ProtoMessage() {}

func (x *SandboxMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxMetricsRequest.ProtoReflect.Descriptor instead.
func (*SandboxMetricsRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{18}
}

func (x *SandboxMetricsRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type SandboxMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *types.Metric          `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxMetricsResponse) Reset() {
	*x = SandboxMetricsResponse{}
	mi := &file_sandbox_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxMetricsResponse) ProtoMessage() {}

func (x *SandboxMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxMetricsResponse.ProtoReflect.Descriptor instead.
func (*SandboxMetricsResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{19}
}

func (x *SandboxMetricsResponse) GetMetrics() *types.Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type CheckpointContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Config        *anypb.Any             `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Status        *anypb.Any             `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointContainer) Reset() {
	*x = CheckpointContainer{}
	mi := &file_sandbox_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointContainer) ProtoMessage() {}

func (x *CheckpointContainer) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointContainer.ProtoReflect.Descriptor instead.
func (*CheckpointContainer) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{20}
}

func (x *CheckpointContainer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckpointContainer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckpointContainer) GetConfig() *anypb.Any {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CheckpointContainer) GetStatus() *anypb.Any {
	if x != nil {
		return x.Status
	}
	return nil
}

type CheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	OutputPath    string                 `protobuf:"bytes,2,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	SandboxConfig *anypb.Any             `protobuf:"bytes,3,opt,name=sandbox_config,json=sandboxConfig,proto3" json:"sandbox_config,omitempty"`
	Containers    []*CheckpointContainer `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	Options       map[string]string      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_sandbox_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{21}
}

func (x *CheckpointRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CheckpointRequest) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *CheckpointRequest) GetSandboxConfig() *anypb.Any {
	if x != nil {
		return x.SandboxConfig
	}
	return nil
}

func (x *CheckpointRequest) GetContainers() []*CheckpointContainer {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *CheckpointRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type CheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_sandbox_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{22}
}

type RestoreContainer struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Config *anypb.Any             `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	// checkpoint_key identifies this container in the checkpoint manifest.
	// The shim uses it to match restore tasks to checkpoint artifacts.
	CheckpointKey string `protobuf:"bytes,4,opt,name=checkpoint_key,json=checkpointKey,proto3" json:"checkpoint_key,omitempty"`
	// Absolute path to the container bundle on the host.
	BundlePath string `protobuf:"bytes,5,opt,name=bundle_path,json=bundlePath,proto3" json:"bundle_path,omitempty"`
	// Whether the container has a terminal (TTY).
	Terminal bool `protobuf:"varint,6,opt,name=terminal,proto3" json:"terminal,omitempty"`
	// Stdio paths for the container.
	Stdin         string `protobuf:"bytes,7,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Stdout        string `protobuf:"bytes,8,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string `protobuf:"bytes,9,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreContainer) Reset() {
	*x = RestoreContainer{}
	mi := &file_sandbox_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreContainer) ProtoMessage() {}

func (x *RestoreContainer) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreContainer.ProtoReflect.Descriptor instead.
func (*RestoreContainer) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{23}
}

func (x *RestoreContainer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RestoreContainer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestoreContainer) GetConfig() *anypb.Any {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RestoreContainer) GetCheckpointKey() string {
	if x != nil {
		return x.CheckpointKey
	}
	return ""
}

func (x *RestoreContainer) GetBundlePath() string {
	if x != nil {
		return x.BundlePath
	}
	return ""
}

func (x *RestoreContainer) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *RestoreContainer) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

func (x *RestoreContainer) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *RestoreContainer) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type RestoreRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SandboxId      string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	CheckpointPath string                 `protobuf:"bytes,2,opt,name=checkpoint_path,json=checkpointPath,proto3" json:"checkpoint_path,omitempty"`
	SandboxConfig  *anypb.Any             `protobuf:"bytes,3,opt,name=sandbox_config,json=sandboxConfig,proto3" json:"sandbox_config,omitempty"`
	Containers     []*RestoreContainer    `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	Options        map[string]string      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Path to the network namespace for the restored sandbox.
	NetnsPath                string            `protobuf:"bytes,6,opt,name=netns_path,json=netnsPath,proto3" json:"netns_path,omitempty"`
	AcceptedTaskRestoreModes []TaskRestoreMode `protobuf:"varint,7,rep,packed,name=accepted_task_restore_modes,json=acceptedTaskRestoreModes,proto3,enum=containerd.runtime.sandbox.v1.TaskRestoreMode" json:"accepted_task_restore_modes,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_sandbox_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{24}
}

func (x *RestoreRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *RestoreRequest) GetCheckpointPath() string {
	if x != nil {
		return x.CheckpointPath
	}
	return ""
}

func (x *RestoreRequest) GetSandboxConfig() *anypb.Any {
	if x != nil {
		return x.SandboxConfig
	}
	return nil
}

func (x *RestoreRequest) GetContainers() []*RestoreContainer {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *RestoreRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *RestoreRequest) GetNetnsPath() string {
	if x != nil {
		return x.NetnsPath
	}
	return ""
}

func (x *RestoreRequest) GetAcceptedTaskRestoreModes() []TaskRestoreMode {
	if x != nil {
		return x.AcceptedTaskRestoreModes
	}
	return nil
}

type RestoredContainer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Ownership transfers from the controller to the caller when Restore
	// succeeds. Empty when no containerd task checkpoint is required.
	TaskCheckpointImage string          `protobuf:"bytes,2,opt,name=task_checkpoint_image,json=taskCheckpointImage,proto3" json:"task_checkpoint_image,omitempty"`
	TaskRestoreMode     TaskRestoreMode `protobuf:"varint,3,opt,name=task_restore_mode,json=taskRestoreMode,proto3,enum=containerd.runtime.sandbox.v1.TaskRestoreMode" json:"task_restore_mode,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RestoredContainer) Reset() {
	*x = RestoredContainer{}
	mi := &file_sandbox_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoredContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoredContainer) ProtoMessage() {}

func (x *RestoredContainer) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoredContainer.ProtoReflect.Descriptor instead.
func (*RestoredContainer) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{25}
}

func (x *RestoredContainer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestoredContainer) GetTaskCheckpointImage() string {
	if x != nil {
		return x.TaskCheckpointImage
	}
	return ""
}

func (x *RestoredContainer) GetTaskRestoreMode() TaskRestoreMode {
	if x != nil {
		return x.TaskRestoreMode
	}
	return TaskRestoreMode_TASK_RESTORE_MODE_UNSPECIFIED
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*RestoredContainer   `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_sandbox_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{26}
}

func (x *RestoreResponse) GetContainers() []*RestoredContainer {
	if x != nil {
		return x.Containers
	}
	return nil
}

var File_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_proto_rawDesc = "" +
	"\n" +
	"\rsandbox.proto\x12\x1dcontainerd.runtime.sandbox.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13types/metrics.proto\x1a\x11types/mount.proto\x1a\x14types/platform.proto\"\xfe\x02\n" +
	"\x14CreateSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vbundle_path\x18\x02 \x01(\tR\n" +
	"bundlePath\x12/\n" +
	"\x06rootfs\x18\x03 \x03(\v2\x17.containerd.types.MountR\x06rootfs\x12.\n" +
	"\aoptions\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\aoptions\x12\x1d\n" +
	"\n" +
	"netns_path\x18\x05 \x01(\tR\tnetnsPath\x12f\n" +
	"\vannotations\x18\x06 \x03(\v2D.containerd.runtime.sandbox.v1.CreateSandboxRequest.AnnotationsEntryR\vannotations\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x17\n" +
	"\x15CreateSandboxResponse\"4\n" +
	"\x13StartSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\x8d\x01\n" +
	"\x14StartSandboxResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12(\n" +
	"\x04spec\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04spec\"0\n" +
	"\x0fPlatformRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"J\n" +
	"\x10PlatformResponse\x126\n" +
	"\bplatform\x18\x01 \x01(\v2\x1a.containerd.types.PlatformR\bplatform\"V\n" +
	"\x12StopSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12!\n" +
	"\ftimeout_secs\x18\x02 \x01(\rR\vtimeoutSecs\"\x15\n" +
	"\x13StopSandboxResponse\"\x91\x02\n" +
	"\x14UpdateSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x122\n" +
	"\tresources\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\tresources\x12f\n" +
	"\vannotations\x18\x03 \x03(\v2D.containerd.runtime.sandbox.v1.UpdateSandboxRequest.AnnotationsEntryR\vannotations\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\x12WaitSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"o\n" +
	"\x13WaitSandboxResponse\x12\x1f\n" +
	"\vexit_status\x18\x01 \x01(\rR\n" +
	"exitStatus\x127\n" +
	"\texited_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bexitedAt\"\x17\n" +
	"\x15UpdateSandboxResponse\"O\n" +
	"\x14SandboxStatusRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x18\n" +
	"\averbose\x18\x02 \x01(\bR\averbose\"\x8b\x03\n" +
	"\x15SandboxStatusResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12R\n" +
	"\x04info\x18\x04 \x03(\v2>.containerd.runtime.sandbox.v1.SandboxStatusResponse.InfoEntryR\x04info\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\texited_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bexitedAt\x12*\n" +
	"\x05extra\x18\a \x01(\v2\x14.google.protobuf.AnyR\x05extra\x1a7\n" +
	"\tInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\vPingRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\x0e\n" +
	"\fPingResponse\"7\n" +
	"\x16ShutdownSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\x19\n" +
	"\x17ShutdownSandboxResponse\"6\n" +
	"\x15SandboxMetricsRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"L\n" +
	"\x16SandboxMetricsResponse\x122\n" +
	"\ametrics\x18\x01 \x01(\v2\x18.containerd.types.MetricR\ametrics\"\x95\x01\n" +
	"\x13CheckpointContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x06config\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x06config\x12,\n" +
	"\x06status\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x06status\"\xf9\x02\n" +
	"\x11CheckpointRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\voutput_path\x18\x02 \x01(\tR\n" +
	"outputPath\x12;\n" +
	"\x0esandbox_config\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\rsandboxConfig\x12R\n" +
	"\n" +
	"containers\x18\x04 \x03(\v22.containerd.runtime.sandbox.v1.CheckpointContainerR\n" +
	"containers\x12W\n" +
	"\aoptions\x18\x05 \x03(\v2=.containerd.runtime.sandbox.v1.CheckpointRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12CheckpointResponse\"\x8e\x02\n" +
	"\x10RestoreContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x06config\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x06config\x12%\n" +
	"\x0echeckpoint_key\x18\x04 \x01(\tR\rcheckpointKey\x12\x1f\n" +
	"\vbundle_path\x18\x05 \x01(\tR\n" +
	"bundlePath\x12\x1a\n" +
	"\bterminal\x18\x06 \x01(\bR\bterminal\x12\x14\n" +
	"\x05stdin\x18\a \x01(\tR\x05stdin\x12\x16\n" +
	"\x06stdout\x18\b \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\t \x01(\tR\x06stderr\"\x86\x04\n" +
	"\x0eRestoreRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12'\n" +
	"\x0fcheckpoint_path\x18\x02 \x01(\tR\x0echeckpointPath\x12;\n" +
	"\x0esandbox_config\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\rsandboxConfig\x12O\n" +
	"\n" +
	"containers\x18\x04 \x03(\v2/.containerd.runtime.sandbox.v1.RestoreContainerR\n" +
	"containers\x12T\n" +
	"\aoptions\x18\x05 \x03(\v2:.containerd.runtime.sandbox.v1.RestoreRequest.OptionsEntryR\aoptions\x12\x1d\n" +
	"\n" +
	"netns_path\x18\x06 \x01(\tR\tnetnsPath\x12m\n" +
	"\x1baccepted_task_restore_modes\x18\a \x03(\x0e2..containerd.runtime.sandbox.v1.TaskRestoreModeR\x18acceptedTaskRestoreModes\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\x11RestoredContainer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x15task_checkpoint_image\x18\x02 \x01(\tR\x13taskCheckpointImage\x12Z\n" +
	"\x11task_restore_mode\x18\x03 \x01(\x0e2..containerd.runtime.sandbox.v1.TaskRestoreModeR\x0ftaskRestoreMode\"c\n" +
	"\x0fRestoreResponse\x12P\n" +
	"\n" +
	"containers\x18\x01 \x03(\v20.containerd.runtime.sandbox.v1.RestoredContainerR\n" +
	"containers*W\n" +
	"\x0fTaskRestoreMode\x12!\n" +
	"\x1dTASK_RESTORE_MODE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dTASK_RESTORE_MODE_VM_RESTORED\x10\x012\xbd\b\n" +
	"\aSandbox\x12z\n" +
	"\rCreateSandbox\x123.containerd.runtime.sandbox.v1.CreateSandboxRequest\x1a4.containerd.runtime.sandbox.v1.CreateSandboxResponse\x12w\n" +
	"\fStartSandbox\x122.containerd.runtime.sandbox.v1.StartSandboxRequest\x1a3.containerd.runtime.sandbox.v1.StartSandboxResponse\x12k\n" +
	"\bPlatform\x12..containerd.runtime.sandbox.v1.PlatformRequest\x1a/.containerd.runtime.sandbox.v1.PlatformResponse\x12t\n" +
	"\vStopSandbox\x121.containerd.runtime.sandbox.v1.StopSandboxRequest\x1a2.containerd.runtime.sandbox.v1.StopSandboxResponse\x12t\n" +
	"\vWaitSandbox\x121.containerd.runtime.sandbox.v1.WaitSandboxRequest\x1a2.containerd.runtime.sandbox.v1.WaitSandboxResponse\x12z\n" +
	"\rSandboxStatus\x123.containerd.runtime.sandbox.v1.SandboxStatusRequest\x1a4.containerd.runtime.sandbox.v1.SandboxStatusResponse\x12f\n" +
	"\vPingSandbox\x12*.containerd.runtime.sandbox.v1.PingRequest\x1a+.containerd.runtime.sandbox.v1.PingResponse\x12\x80\x01\n" +
	"\x0fShutdownSandbox\x125.containerd.runtime.sandbox.v1.ShutdownSandboxRequest\x1a6.containerd.runtime.sandbox.v1.ShutdownSandboxResponse\x12}\n" +
	"\x0eSandboxMetrics\x124.containerd.runtime.sandbox.v1.SandboxMetricsRequest\x1a5.containerd.runtime.sandbox.v1.SandboxMetricsResponse2\xe9\x01\n" +
	"\n" +
	"Checkpoint\x12q\n" +
	"\n" +
	"Checkpoint\x120.containerd.runtime.sandbox.v1.CheckpointRequest\x1a1.containerd.runtime.sandbox.v1.CheckpointResponse\x12h\n" +
	"\aRestore\x12-.containerd.runtime.sandbox.v1.RestoreRequest\x1a..containerd.runtime.sandbox.v1.RestoreResponseBKZIgithub.com/agent-substrate/substrate/internal/sandboxd/sandboxapi;sandboxb\x06proto3"

var (
	file_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_proto_rawDescData []byte
)

func file_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)))
	})
	return file_sandbox_proto_rawDescData
}

var file_sandbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_sandbox_proto_goTypes = []any{
	(TaskRestoreMode)(0),            // 0: containerd.runtime.sandbox.v1.TaskRestoreMode
	(*CreateSandboxRequest)(nil),    // 1: containerd.runtime.sandbox.v1.CreateSandboxRequest
	(*CreateSandboxResponse)(nil),   // 2: containerd.runtime.sandbox.v1.CreateSandboxResponse
	(*StartSandboxRequest)(nil),     // 3: containerd.runtime.sandbox.v1.StartSandboxRequest
	(*StartSandboxResponse)(nil),    // 4: containerd.runtime.sandbox.v1.StartSandboxResponse
	(*PlatformRequest)(nil),         // 5: containerd.runtime.sandbox.v1.PlatformRequest
	(*PlatformResponse)(nil),        // 6: containerd.runtime.sandbox.v1.PlatformResponse
	(*StopSandboxRequest)(nil),      // 7: containerd.runtime.sandbox.v1.StopSandboxRequest
	(*StopSandboxResponse)(nil),     // 8: containerd.runtime.sandbox.v1.StopSandboxResponse
	(*UpdateSandboxRequest)(nil),    // 9: containerd.runtime.sandbox.v1.UpdateSandboxRequest
	(*WaitSandboxRequest)(nil),      // 10: containerd.runtime.sandbox.v1.WaitSandboxRequest
	(*WaitSandboxResponse)(nil),     // 11: containerd.runtime.sandbox.v1.WaitSandboxResponse
	(*UpdateSandboxResponse)(nil),   // 12: containerd.runtime.sandbox.v1.UpdateSandboxResponse
	(*SandboxStatusRequest)(nil),    // 13: containerd.runtime.sandbox.v1.SandboxStatusRequest
	(*SandboxStatusResponse)(nil),   // 14: containerd.runtime.sandbox.v1.SandboxStatusResponse
	(*PingRequest)(nil),             // 15: containerd.runtime.sandbox.v1.PingRequest
	(*PingResponse)(nil),            // 16: containerd.runtime.sandbox.v1.PingResponse
	(*ShutdownSandboxRequest)(nil),  // 17: containerd.runtime.sandbox.v1.ShutdownSandboxRequest
	(*ShutdownSandboxResponse)(nil), // 18: containerd.runtime.sandbox.v1.ShutdownSandboxResponse
	(*SandboxMetricsRequest)(nil),   // 19: containerd.runtime.sandbox.v1.SandboxMetricsRequest
	(*SandboxMetricsResponse)(nil),  // 20: containerd.runtime.sandbox.v1.SandboxMetricsResponse
	(*CheckpointContainer)(nil),     // 21: containerd.runtime.sandbox.v1.CheckpointContainer
	(*CheckpointRequest)(nil),       // 22: containerd.runtime.sandbox.v1.CheckpointRequest
	(*CheckpointResponse)(nil),      // 23: containerd.runtime.sandbox.v1.CheckpointResponse
	(*RestoreContainer)(nil),        // 24: containerd.runtime.sandbox.v1.RestoreContainer
	(*RestoreRequest)(nil),          // 25: containerd.runtime.sandbox.v1.RestoreRequest
	(*RestoredContainer)(nil),       // 26: containerd.runtime.sandbox.v1.RestoredContainer
	(*RestoreResponse)(nil),         // 27: containerd.runtime.sandbox.v1.RestoreResponse
	nil,                             // 28: containerd.runtime.sandbox.v1.CreateSandboxRequest.AnnotationsEntry
	nil,                             // 29: containerd.runtime.sandbox.v1.UpdateSandboxRequest.AnnotationsEntry
	nil,                             // 30: containerd.runtime.sandbox.v1.SandboxStatusResponse.InfoEntry
	nil,                             // 31: containerd.runtime.sandbox.v1.CheckpointRequest.OptionsEntry
	nil,                             // 32: containerd.runtime.sandbox.v1.RestoreRequest.OptionsEntry
	(*types.Mount)(nil),             // 33: containerd.types.Mount
	(*anypb.Any)(nil),               // 34: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),   // 35: google.protobuf.Timestamp
	(*types.Platform)(nil),          // 36: containerd.types.Platform
	(*types.Metric)(nil),            // 37: containerd.types.Metric
}
var file_sandbox_proto_depIdxs = []int32{
	33, // 0: containerd.runtime.sandbox.v1.CreateSandboxRequest.rootfs:type_name -> containerd.types.Mount
	34, // 1: containerd.runtime.sandbox.v1.CreateSandboxRequest.options:type_name -> google.protobuf.Any
	28, // 2: containerd.runtime.sandbox.v1.CreateSandboxRequest.annotations:type_name -> containerd.runtime.sandbox.v1.CreateSandboxRequest.AnnotationsEntry
	35, // 3: containerd.runtime.sandbox.v1.StartSandboxResponse.created_at:type_name -> google.protobuf.Timestamp
	34, // 4: containerd.runtime.sandbox.v1.StartSandboxResponse.spec:type_name -> google.protobuf.Any
	36, // 5: containerd.runtime.sandbox.v1.PlatformResponse.platform:type_name -> containerd.types.Platform
	34, // 6: containerd.runtime.sandbox.v1.UpdateSandboxRequest.resources:type_name -> google.protobuf.Any
	29, // 7: containerd.runtime.sandbox.v1.UpdateSandboxRequest.annotations:type_name -> containerd.runtime.sandbox.v1.UpdateSandboxRequest.AnnotationsEntry
	35, // 8: containerd.runtime.sandbox.v1.WaitSandboxResponse.exited_at:type_name -> google.protobuf.Timestamp
	30, // 9: containerd.runtime.sandbox.v1.SandboxStatusResponse.info:type_name -> containerd.runtime.sandbox.v1.SandboxStatusResponse.InfoEntry
	35, // 10: containerd.runtime.sandbox.v1.SandboxStatusResponse.created_at:type_name -> google.protobuf.Timestamp
	35, // 11: containerd.runtime.sandbox.v1.SandboxStatusResponse.exited_at:type_name -> google.protobuf.Timestamp
	34, // 12: containerd.runtime.sandbox.v1.SandboxStatusResponse.extra:type_name -> google.protobuf.Any
	37, // 13: containerd.runtime.sandbox.v1.SandboxMetricsResponse.metrics:type_name -> containerd.types.Metric
	34, // 14: containerd.runtime.sandbox.v1.CheckpointContainer.config:type_name -> google.protobuf.Any
	34, // 15: containerd.runtime.sandbox.v1.CheckpointContainer.status:type_name -> google.protobuf.Any
	34, // 16: containerd.runtime.sandbox.v1.CheckpointRequest.sandbox_config:type_name -> google.protobuf.Any
	21, // 17: containerd.runtime.sandbox.v1.CheckpointRequest.containers:type_name -> containerd.runtime.sandbox.v1.CheckpointContainer
	31, // 18: containerd.runtime.sandbox.v1.CheckpointRequest.options:type_name -> containerd.runtime.sandbox.v1.CheckpointRequest.OptionsEntry
	34, // 19: containerd.runtime.sandbox.v1.RestoreContainer.config:type_name -> google.protobuf.Any
	34, // 20: containerd.runtime.sandbox.v1.RestoreRequest.sandbox_config:type_name -> google.protobuf.Any
	24, // 21: containerd.runtime.sandbox.v1.RestoreRequest.containers:type_name -> containerd.runtime.sandbox.v1.RestoreContainer
	32, // 22: containerd.runtime.sandbox.v1.RestoreRequest.options:type_name -> containerd.runtime.sandbox.v1.RestoreRequest.OptionsEntry
	0,  // 23: containerd.runtime.sandbox.v1.RestoreRequest.accepted_task_restore_modes:type_name -> containerd.runtime.sandbox.v1.TaskRestoreMode
	0,  // 24: containerd.runtime.sandbox.v1.RestoredContainer.task_restore_mode:type_name -> containerd.runtime.sandbox.v1.TaskRestoreMode
	26, // 25: containerd.runtime.sandbox.v1.RestoreResponse.containers:type_name -> containerd.runtime.sandbox.v1.RestoredContainer
	1,  // 26: containerd.runtime.sandbox.v1.Sandbox.CreateSandbox:input_type -> containerd.runtime.sandbox.v1.CreateSandboxRequest
	3,  // 27: containerd.runtime.sandbox.v1.Sandbox.StartSandbox:input_type -> containerd.runtime.sandbox.v1.StartSandboxRequest
	5,  // 28: containerd.runtime.sandbox.v1.Sandbox.Platform:input_type -> containerd.runtime.sandbox.v1.PlatformRequest
	7,  // 29: containerd.runtime.sandbox.v1.Sandbox.StopSandbox:input_type -> containerd.runtime.sandbox.v1.StopSandboxRequest
	10, // 30: containerd.runtime.sandbox.v1.Sandbox.WaitSandbox:input_type -> containerd.runtime.sandbox.v1.WaitSandboxRequest
	13, // 31: containerd.runtime.sandbox.v1.Sandbox.SandboxStatus:input_type -> containerd.runtime.sandbox.v1.SandboxStatusRequest
	15, // 32: containerd.runtime.sandbox.v1.Sandbox.PingSandbox:input_type -> containerd.runtime.sandbox.v1.PingRequest
	17, // 33: containerd.runtime.sandbox.v1.Sandbox.ShutdownSandbox:input_type -> containerd.runtime.sandbox.v1.ShutdownSandboxRequest
	19, // 34: containerd.runtime.sandbox.v1.Sandbox.SandboxMetrics:input_type -> containerd.runtime.sandbox.v1.SandboxMetricsRequest
	22, // 35: containerd.runtime.sandbox.v1.Checkpoint.Checkpoint:input_type -> containerd.runtime.sandbox.v1.CheckpointRequest
	25, // 36: containerd.runtime.sandbox.v1.Checkpoint.Restore:input_type -> containerd.runtime.sandbox.v1.RestoreRequest
	2,  // 37: containerd.runtime.sandbox.v1.Sandbox.CreateSandbox:output_type -> containerd.runtime.sandbox.v1.CreateSandboxResponse
	4,  // 38: containerd.runtime.sandbox.v1.Sandbox.StartSandbox:output_type -> containerd.runtime.sandbox.v1.StartSandboxResponse
	6,  // 39: containerd.runtime.sandbox.v1.Sandbox.Platform:output_type -> containerd.runtime.sandbox.v1.PlatformResponse
	8,  // 40: containerd.runtime.sandbox.v1.Sandbox.StopSandbox:output_type -> containerd.runtime.sandbox.v1.StopSandboxResponse
	11, // 41: containerd.runtime.sandbox.v1.Sandbox.WaitSandbox:output_type -> containerd.runtime.sandbox.v1.WaitSandboxResponse
	14, // 42: containerd.runtime.sandbox.v1.Sandbox.SandboxStatus:output_type -> containerd.runtime.sandbox.v1.SandboxStatusResponse
	16, // 43: containerd.runtime.sandbox.v1.Sandbox.PingSandbox:output_type -> containerd.runtime.sandbox.v1.PingResponse
	18, // 44: containerd.runtime.sandbox.v1.Sandbox.ShutdownSandbox:output_type -> containerd.runtime.sandbox.v1.ShutdownSandboxResponse
	20, // 45: containerd.runtime.sandbox.v1.Sandbox.SandboxMetrics:output_type -> containerd.runtime.sandbox.v1.SandboxMetricsResponse
	23, // 46: containerd.runtime.sandbox.v1.Checkpoint.Checkpoint:output_type -> containerd.runtime.sandbox.v1.CheckpointResponse
	27, // 47: containerd.runtime.sandbox.v1.Checkpoint.Restore:output_type -> containerd.runtime.sandbox.v1.RestoreResponse
	37, // [37:48] is the sub-list for method output_type
	26, // [26:37] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_sandbox_proto_init() }
func file_sandbox_proto_init() {
	if File_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_proto_depIdxs,
		EnumInfos:         file_sandbox_proto_enumTypes,
		MessageInfos:      file_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_proto = out.File
	file_sandbox_proto_goTypes = nil
	file_sandbox_proto_depIdxs = nil
}
