apiVersion: v1
kind: Namespace
metadata:
  name: egress-https-target
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-https-echo
  namespace: egress-https-target
  labels:
    app: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo-server
        image: mendhak/http-https-echo:latest
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        env:
        - name: ECHO_INCLUDE_ENV_VARS
          value: "0" # Set to "1" if you want pod env vars dumped in the response
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: egress-https-target
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: echo-server
