// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: snapshots.proto

package snapshots

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_snapshots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{0}
}

func (x *Mount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Mount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Mount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Mount) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type PrepareSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshotter   string                 `protobuf:"bytes,1,opt,name=snapshotter,proto3" json:"snapshotter,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Parent        string                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareSnapshotRequest) Reset() {
	*x = PrepareSnapshotRequest{}
	mi := &file_snapshots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareSnapshotRequest) ProtoMessage() {}

func (x *PrepareSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareSnapshotRequest.ProtoReflect.Descriptor instead.
func (*PrepareSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareSnapshotRequest) GetSnapshotter() string {
	if x != nil {
		return x.Snapshotter
	}
	return ""
}

func (x *PrepareSnapshotRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PrepareSnapshotRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *PrepareSnapshotRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type PrepareSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mounts        []*Mount               `protobuf:"bytes,1,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareSnapshotResponse) Reset() {
	*x = PrepareSnapshotResponse{}
	mi := &file_snapshots_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareSnapshotResponse) ProtoMessage() {}

func (x *PrepareSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareSnapshotResponse.ProtoReflect.Descriptor instead.
func (*PrepareSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareSnapshotResponse) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type ViewSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshotter   string                 `protobuf:"bytes,1,opt,name=snapshotter,proto3" json:"snapshotter,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Parent        string                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewSnapshotRequest) Reset() {
	*x = ViewSnapshotRequest{}
	mi := &file_snapshots_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewSnapshotRequest) ProtoMessage() {}

func (x *ViewSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ViewSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{3}
}

func (x *ViewSnapshotRequest) GetSnapshotter() string {
	if x != nil {
		return x.Snapshotter
	}
	return ""
}

func (x *ViewSnapshotRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ViewSnapshotRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ViewSnapshotRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ViewSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mounts        []*Mount               `protobuf:"bytes,1,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewSnapshotResponse) Reset() {
	*x = ViewSnapshotResponse{}
	mi := &file_snapshots_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewSnapshotResponse) ProtoMessage() {}

func (x *ViewSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewSnapshotResponse.ProtoReflect.Descriptor instead.
func (*ViewSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{4}
}

func (x *ViewSnapshotResponse) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type MountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshotter   string                 `protobuf:"bytes,1,opt,name=snapshotter,proto3" json:"snapshotter,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountsRequest) Reset() {
	*x = MountsRequest{}
	mi := &file_snapshots_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountsRequest) ProtoMessage() {}

func (x *MountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountsRequest.ProtoReflect.Descriptor instead.
func (*MountsRequest) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{5}
}

func (x *MountsRequest) GetSnapshotter() string {
	if x != nil {
		return x.Snapshotter
	}
	return ""
}

func (x *MountsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type MountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mounts        []*Mount               `protobuf:"bytes,1,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountsResponse) Reset() {
	*x = MountsResponse{}
	mi := &file_snapshots_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountsResponse) ProtoMessage() {}

func (x *MountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountsResponse.ProtoReflect.Descriptor instead.
func (*MountsResponse) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{6}
}

func (x *MountsResponse) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type RemoveSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshotter   string                 `protobuf:"bytes,1,opt,name=snapshotter,proto3" json:"snapshotter,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSnapshotRequest) Reset() {
	*x = RemoveSnapshotRequest{}
	mi := &file_snapshots_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSnapshotRequest) ProtoMessage() {}

func (x *RemoveSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSnapshotRequest.ProtoReflect.Descriptor instead.
func (*RemoveSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveSnapshotRequest) GetSnapshotter() string {
	if x != nil {
		return x.Snapshotter
	}
	return ""
}

func (x *RemoveSnapshotRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type StatSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshotter   string                 `protobuf:"bytes,1,opt,name=snapshotter,proto3" json:"snapshotter,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatSnapshotRequest) Reset() {
	*x = StatSnapshotRequest{}
	mi := &file_snapshots_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatSnapshotRequest) ProtoMessage() {}

func (x *StatSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatSnapshotRequest.ProtoReflect.Descriptor instead.
func (*StatSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{8}
}

func (x *StatSnapshotRequest) GetSnapshotter() string {
	if x != nil {
		return x.Snapshotter
	}
	return ""
}

func (x *StatSnapshotRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parent        string                 `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_snapshots_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{9}
}

func (x *Info) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Info) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *Info) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type StatSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *Info                  `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatSnapshotResponse) Reset() {
	*x = StatSnapshotResponse{}
	mi := &file_snapshots_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatSnapshotResponse) ProtoMessage() {}

func (x *StatSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatSnapshotResponse.ProtoReflect.Descriptor instead.
func (*StatSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshots_proto_rawDescGZIP(), []int{10}
}

func (x *StatSnapshotResponse) GetInfo() *Info {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_snapshots_proto protoreflect.FileDescriptor

const file_snapshots_proto_rawDesc = "" +
	"\n" +
	"\x0fsnapshots.proto\x12 containerd.services.snapshots.v1\x1a\x1bgoogle/protobuf/empty.proto\"e\n" +
	"\x05Mount\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\"\xfd\x01\n" +
	"\x16PrepareSnapshotRequest\x12 \n" +
	"\vsnapshotter\x18\x01 \x01(\tR\vsnapshotter\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\x12\\\n" +
	"\x06labels\x18\x04 \x03(\v2D.containerd.services.snapshots.v1.PrepareSnapshotRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\x17PrepareSnapshotResponse\x12?\n" +
	"\x06mounts\x18\x01 \x03(\v2'.containerd.services.snapshots.v1.MountR\x06mounts\"\xf7\x01\n" +
	"\x13ViewSnapshotRequest\x12 \n" +
	"\vsnapshotter\x18\x01 \x01(\tR\vsnapshotter\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\x12Y\n" +
	"\x06labels\x18\x04 \x03(\v2A.containerd.services.snapshots.v1.ViewSnapshotRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\x14ViewSnapshotResponse\x12?\n" +
	"\x06mounts\x18\x01 \x03(\v2'.containerd.services.snapshots.v1.MountR\x06mounts\"C\n" +
	"\rMountsRequest\x12 \n" +
	"\vsnapshotter\x18\x01 \x01(\tR\vsnapshotter\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"Q\n" +
	"\x0eMountsResponse\x12?\n" +
	"\x06mounts\x18\x01 \x03(\v2'.containerd.services.snapshots.v1.MountR\x06mounts\"K\n" +
	"\x15RemoveSnapshotRequest\x12 \n" +
	"\vsnapshotter\x18\x01 \x01(\tR\vsnapshotter\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"I\n" +
	"\x13StatSnapshotRequest\x12 \n" +
	"\vsnapshotter\x18\x01 \x01(\tR\vsnapshotter\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\xb9\x01\n" +
	"\x04Info\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\tR\x06parent\x12J\n" +
	"\x06labels\x18\x03 \x03(\v22.containerd.services.snapshots.v1.Info.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x14StatSnapshotResponse\x12:\n" +
	"\x04info\x18\x01 \x01(\v2&.containerd.services.snapshots.v1.InfoR\x04info2\xc1\x04\n" +
	"\tSnapshots\x12~\n" +
	"\aPrepare\x128.containerd.services.snapshots.v1.PrepareSnapshotRequest\x1a9.containerd.services.snapshots.v1.PrepareSnapshotResponse\x12u\n" +
	"\x04View\x125.containerd.services.snapshots.v1.ViewSnapshotRequest\x1a6.containerd.services.snapshots.v1.ViewSnapshotResponse\x12k\n" +
	"\x06Mounts\x12/.containerd.services.snapshots.v1.MountsRequest\x1a0.containerd.services.snapshots.v1.MountsResponse\x12Y\n" +
	"\x06Remove\x127.containerd.services.snapshots.v1.RemoveSnapshotRequest\x1a\x16.google.protobuf.Empty\x12u\n" +
	"\x04Stat\x125.containerd.services.snapshots.v1.StatSnapshotRequest\x1a6.containerd.services.snapshots.v1.StatSnapshotResponseB?Z=github.com/agent-substrate/substrate/internal/proto/snapshotsb\x06proto3"

var (
	file_snapshots_proto_rawDescOnce sync.Once
	file_snapshots_proto_rawDescData []byte
)

func file_snapshots_proto_rawDescGZIP() []byte {
	file_snapshots_proto_rawDescOnce.Do(func() {
		file_snapshots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshots_proto_rawDesc), len(file_snapshots_proto_rawDesc)))
	})
	return file_snapshots_proto_rawDescData
}

var file_snapshots_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_snapshots_proto_goTypes = []any{
	(*Mount)(nil),                   // 0: containerd.services.snapshots.v1.Mount
	(*PrepareSnapshotRequest)(nil),  // 1: containerd.services.snapshots.v1.PrepareSnapshotRequest
	(*PrepareSnapshotResponse)(nil), // 2: containerd.services.snapshots.v1.PrepareSnapshotResponse
	(*ViewSnapshotRequest)(nil),     // 3: containerd.services.snapshots.v1.ViewSnapshotRequest
	(*ViewSnapshotResponse)(nil),    // 4: containerd.services.snapshots.v1.ViewSnapshotResponse
	(*MountsRequest)(nil),           // 5: containerd.services.snapshots.v1.MountsRequest
	(*MountsResponse)(nil),          // 6: containerd.services.snapshots.v1.MountsResponse
	(*RemoveSnapshotRequest)(nil),   // 7: containerd.services.snapshots.v1.RemoveSnapshotRequest
	(*StatSnapshotRequest)(nil),     // 8: containerd.services.snapshots.v1.StatSnapshotRequest
	(*Info)(nil),                    // 9: containerd.services.snapshots.v1.Info
	(*StatSnapshotResponse)(nil),    // 10: containerd.services.snapshots.v1.StatSnapshotResponse
	nil,                             // 11: containerd.services.snapshots.v1.PrepareSnapshotRequest.LabelsEntry
	nil,                             // 12: containerd.services.snapshots.v1.ViewSnapshotRequest.LabelsEntry
	nil,                             // 13: containerd.services.snapshots.v1.Info.LabelsEntry
	(*emptypb.Empty)(nil),           // 14: google.protobuf.Empty
}
var file_snapshots_proto_depIdxs = []int32{
	11, // 0: containerd.services.snapshots.v1.PrepareSnapshotRequest.labels:type_name -> containerd.services.snapshots.v1.PrepareSnapshotRequest.LabelsEntry
	0,  // 1: containerd.services.snapshots.v1.PrepareSnapshotResponse.mounts:type_name -> containerd.services.snapshots.v1.Mount
	12, // 2: containerd.services.snapshots.v1.ViewSnapshotRequest.labels:type_name -> containerd.services.snapshots.v1.ViewSnapshotRequest.LabelsEntry
	0,  // 3: containerd.services.snapshots.v1.ViewSnapshotResponse.mounts:type_name -> containerd.services.snapshots.v1.Mount
	0,  // 4: containerd.services.snapshots.v1.MountsResponse.mounts:type_name -> containerd.services.snapshots.v1.Mount
	13, // 5: containerd.services.snapshots.v1.Info.labels:type_name -> containerd.services.snapshots.v1.Info.LabelsEntry
	9,  // 6: containerd.services.snapshots.v1.StatSnapshotResponse.info:type_name -> containerd.services.snapshots.v1.Info
	1,  // 7: containerd.services.snapshots.v1.Snapshots.Prepare:input_type -> containerd.services.snapshots.v1.PrepareSnapshotRequest
	3,  // 8: containerd.services.snapshots.v1.Snapshots.View:input_type -> containerd.services.snapshots.v1.ViewSnapshotRequest
	5,  // 9: containerd.services.snapshots.v1.Snapshots.Mounts:input_type -> containerd.services.snapshots.v1.MountsRequest
	7,  // 10: containerd.services.snapshots.v1.Snapshots.Remove:input_type -> containerd.services.snapshots.v1.RemoveSnapshotRequest
	8,  // 11: containerd.services.snapshots.v1.Snapshots.Stat:input_type -> containerd.services.snapshots.v1.StatSnapshotRequest
	2,  // 12: containerd.services.snapshots.v1.Snapshots.Prepare:output_type -> containerd.services.snapshots.v1.PrepareSnapshotResponse
	4,  // 13: containerd.services.snapshots.v1.Snapshots.View:output_type -> containerd.services.snapshots.v1.ViewSnapshotResponse
	6,  // 14: containerd.services.snapshots.v1.Snapshots.Mounts:output_type -> containerd.services.snapshots.v1.MountsResponse
	14, // 15: containerd.services.snapshots.v1.Snapshots.Remove:output_type -> google.protobuf.Empty
	10, // 16: containerd.services.snapshots.v1.Snapshots.Stat:output_type -> containerd.services.snapshots.v1.StatSnapshotResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_snapshots_proto_init() }
func file_snapshots_proto_init() {
	if File_snapshots_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshots_proto_rawDesc), len(file_snapshots_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snapshots_proto_goTypes,
		DependencyIndexes: file_snapshots_proto_depIdxs,
		MessageInfos:      file_snapshots_proto_msgTypes,
	}.Build()
	File_snapshots_proto = out.File
	file_snapshots_proto_goTypes = nil
	file_snapshots_proto_depIdxs = nil
}
